import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';
import { Project } from '@/lib/models';
import { verifyAdminToken } from '@/lib/auth';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

const INITIAL_PROJECTS = [
  {
    title: 'Smart Kisan AI – Agritech Platform',
    subtitle: 'AI crop yield recommendation, plant disease diagnosis & live market prices',
    description: 'AI-driven smart agriculture platform providing crop recommendation, plant leaf disease detection using computer vision, real-time market price predictions, soil telemetry, and an AI farming assistant.',
    longDescription: 'Comprehensive agritech ecosystem helping farmers optimize crop yields, detect crop diseases using deep neural networks, monitor soil metrics, track live mandi prices, and consult an AI agronomist.',
    category: 'AI & ML',
    tags: ['Python', 'Flask', 'FastAPI', 'TensorFlow', 'OpenCV', 'React', 'Node.js', 'Tailwind CSS', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439/Smart-Kisan-Final',
    liveUrl: 'https://github.com/Krishna8208863439/Smart-Kisan-Final',
    featured: true,
  },
  {
    title: 'CodeRush 2.0 – Competitive Coding Platform',
    subtitle: 'Real-time coding contest & isolated execution sandbox',
    description: 'Real-time competitive programming platform built for CodeWarriors hackathon, featuring instant code execution sandbox, algorithmic problem sets, automated scoring, and live leaderboards.',
    longDescription: 'Full stack developer contest platform with multi-language code runner sandbox, real-time scoreboard via WebSockets, and automated test suite verification.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'Node.js', 'Docker Sandbox', 'WebSockets', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'End-to-End AI Medical Chatbot',
    subtitle: 'RAG-powered health assistant for medical triage & symptom diagnosis',
    description: 'RAG-powered conversational medical chatbot trained on healthcare datasets for symptom evaluation, medical triage guidance, and prescription information.',
    longDescription: 'AI healthcare assistant utilizing Retrieval-Augmented Generation (RAG) and vector databases to parse clinical medical manuals, provide instant symptom advice, and answer medical queries.',
    category: 'AI & ML',
    tags: ['Python', 'LangChain', 'Pinecone', 'OpenAI API', 'Flask', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart Healthcare Diagnostics System',
    subtitle: 'Unified digital medical portal & patient telemetry',
    description: 'Comprehensive medical diagnostics and hospital portal connecting patient EMR records, virtual doctor consultations, lab report analysis, and disease risk scoring.',
    longDescription: 'End-to-end healthcare web platform featuring electronic medical records (EMR), live doctor booking, AI diagnostic risk scoring, and secure medical data vaulting.',
    category: 'Full Stack',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Python', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Snake Game with AI Twist',
    subtitle: 'Reinforcement Learning & AI-powered arcade game',
    description: 'Interactive modern arcade Snake game enhanced with Reinforcement Learning (Q-learning AI mode), adaptive difficulty obstacles, and dynamic visual themes.',
    longDescription: 'Browser arcade game combining classic gameplay with autonomous AI bot mode powered by Q-learning algorithms and dynamic pathfinding.',
    category: 'AI & ML',
    tags: ['JavaScript', 'TypeScript', 'Python', 'Pygame', 'HTML5 Canvas', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'SageCommand AI Production Hub',
    subtitle: 'Autonomous AI command console & workflow orchestrator',
    description: 'Enterprise-grade autonomous AI command console orchestrating LLM agent workflows, automated prompt chains, script execution, and cloud telemetry monitoring.',
    longDescription: 'Production-ready AI command center enabling enterprise teams to trigger multi-agent task pipelines, monitor LLM API usage, and inspect autonomous logs.',
    category: 'AI & ML',
    tags: ['Python', 'FastAPI', 'React', 'Docker', 'Tailwind CSS', 'LangChain'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Autonomous Multi-Agent Workspace',
    subtitle: 'Multi-agent collaboration engine & browser automation',
    description: 'Autonomous task execution framework where specialized planner, browser researcher, code builder, and reviewer AI agents collaborate to fulfill complex developer goals.',
    longDescription: 'Autonomous multi-agent system coordinating specialized AI subagents with tool execution, browser automation, web search, and code synthesis.',
    category: 'AI & ML',
    tags: ['Python', 'LangChain', 'CrewAI', 'FastAPI', 'React', 'Next.js'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Online Examination & Assessment Portal',
    subtitle: 'Proctored online exam platform with anti-cheat detection',
    description: 'Proctored digital examination portal featuring tab-switch anti-cheating alerts, timed question sets, automated instant grading, and detailed performance analytics.',
    longDescription: 'Educational assessment engine enforcing strict proctoring rules, randomized question shuffling, instant score calculation, and student analytics.',
    category: 'Full Stack',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Bangalore Smart Transport Network',
    subtitle: 'Metropolitan bus/metro live tracking & QR ticketing',
    description: 'Intelligent urban transport platform for metropolitan route planning, live bus and metro GPS telemetry, digital QR ticketing, and transit crowding analytics.',
    longDescription: 'City transport tracking hub providing commuters with live bus locations, estimated arrival times, digital QR passes, and traffic congestion feeds.',
    category: 'Full Stack',
    tags: ['React', 'Node.js', 'Leaflet', 'WebSockets', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Pune Civic & Grievance Portal',
    subtitle: 'Geo-tagged municipal complaint & public service hub',
    description: 'Smart city civic application for citizen grievance reporting, geo-tagged photo uploads, department SLA tracking, emergency alerts, and municipal updates.',
    longDescription: 'Municipal civic engagement platform connecting citizens with urban governance for quick resolution of infrastructure issues and public complaints.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart Mall Management Portal',
    subtitle: 'Store directory kiosk & parking reservation hub',
    description: 'Shopping mall directory platform featuring interactive store maps, promotional deals showcase, customer feedback, and automated parking spot reservations.',
    longDescription: 'Digital shopping mall application providing store location maps, promotional deal banners, interactive store cataloging, and real-time parking slot bookings.',
    category: 'Web',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  // Image 1
  {
    title: 'Waste Management System',
    description: 'Smart IoT & AI-driven municipal waste tracking, bin capacity sensor monitoring, and automated garbage collection route optimization.',
    longDescription: 'End-to-end municipal waste tracking system using sensor telemetry and AI route planning to minimize fuel usage and eliminate overflow bins.',
    category: 'Full Stack',
    tags: ['React', 'Node.js', 'IoT Sensors', 'MongoDB', 'Express'],
    image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart City Operating System',
    description: 'Centralized urban management platform visualizing traffic telemetry, energy grid status, emergency dispatch, and environmental sensor data.',
    longDescription: 'Interactive command dashboard giving city controllers real-time metrics across public transit, power grids, emergency services, and air quality.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'WebSockets', 'Tailwind CSS', 'Recharts'],
    image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'E-Commerce Analytics Hub',
    description: 'Real-time sales performance, customer LTV forecasting, conversion funnel tracking, and inventory telemetry dashboard.',
    longDescription: 'High-conversion analytics engine analyzing sales funnels, cart abandonment rates, and revenue projections.',
    category: 'Web',
    tags: ['React', 'Next.js', 'Tailwind CSS', 'PostgreSQL', 'Chart.js'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Shade Match Studio',
    description: 'AI computer vision application analyzing user facial photos under ambient light to recommend exact cosmetic foundation shades.',
    longDescription: 'Computer vision shade analyzer fine-tuned on diverse skin tone datasets to deliver accurate cosmetic color matching.',
    category: 'AI & ML',
    tags: ['Python', 'OpenCV', 'TensorFlow', 'React', 'FastAPI'],
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Crisis Response Center',
    description: 'Emergency disaster response coordination platform mapping incidents, resource distribution, and real-time survivor SOS alerts.',
    longDescription: 'Disaster management hub connecting first responders, relief centers, and affected citizens with live map routing.',
    category: 'Full Stack',
    tags: ['Next.js', 'Leaflet', 'Node.js', 'WebSockets', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Gallery App',
    description: 'High-speed cloud image vault with automated AI auto-tagging, face grouping, spatial search, and seamless drag-and-drop uploads.',
    longDescription: 'Personal photo management suite using deep neural networks to automatically index and search photo collections.',
    category: 'Web',
    tags: ['React', 'Next.js', 'Cloudinary', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Library Management System',
    description: 'Digital cataloging, RFID book issuance, fine tracking, automated reminder dispatch, and reader borrowing telemetry.',
    longDescription: 'Automated library administration portal tracking physical books, digital loans, reader memberships, and return schedules.',
    category: 'Backend & Cloud',
    tags: ['Node.js', 'Express', 'MySQL', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Restaurant Billing System',
    description: 'POS point-of-sale touch system featuring kitchen display routing, table QR ordering, digital receipts, and inventory deductions.',
    longDescription: 'High-speed restaurant billing software streamlining kitchen communication, customer table orders, and daily revenue reports.',
    category: 'Full Stack',
    tags: ['React', 'Electron', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Password Manager Vault',
    description: 'Zero-knowledge AES-256 encrypted credential vault with master key derivative hashing, breach alerts, and 2FA generator.',
    longDescription: 'Secure password locker utilizing local client encryption before sync, preventing unauthorized data breaches.',
    category: 'Backend & Cloud',
    tags: ['React', 'TypeScript', 'CryptoJS', 'Node.js', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Hotel Booking Management System',
    description: 'Comprehensive property reservation platform with dynamic room pricing, seasonal availability calendars, and payment gateway.',
    longDescription: 'Full hotel operations management tool handling online bookings, room cleaning status, guest check-ins, and billing.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'Stripe', 'PostgreSQL', 'Prisma'],
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Startup Empire Simulator',
    description: 'Gamified business simulation web app modeling venture capital funding, product development cycles, and customer acquisition curves.',
    longDescription: 'Interactive strategy web game modeling startup economics, engineering hires, marketing campaigns, and investor pitches.',
    category: 'Web',
    tags: ['React', 'TypeScript', 'Canvas API', 'Tailwind CSS', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Intelligence Investigation Board',
    description: 'Interactive node graph visualization board for law enforcement data link analysis, suspect connections, and timeline evidence.',
    longDescription: 'Graph network analytics application connecting complex case evidence, financial transactions, and suspect communication channels.',
    category: 'AI & ML',
    tags: ['React', 'Cytoscape.js', 'Python', 'FastAPI', 'Neo4j'],
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Founder Operating System',
    description: 'All-in-one founder workspace managing investor CRM, runway calculation, KPI metrics, task execution, and team delegation.',
    longDescription: 'Central command portal for startup founders tracking burn rates, cap tables, key metrics, and team milestones.',
    category: 'Web',
    tags: ['Next.js', 'React', 'Tailwind CSS', 'Supabase', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Relationship Intelligence CRM',
    description: 'AI-assisted customer contact relationship manager predicting outreach timing, sentiment analysis, and relationship health scores.',
    longDescription: 'Smart CRM analyzing interaction frequency and conversation tone to score customer satisfaction and retention likelihood.',
    category: 'AI & ML',
    tags: ['React', 'Node.js', 'OpenAI API', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Wealth DNA Financial Hub',
    description: 'Personalized wealth building platform aggregating investments, crypto portfolios, tax optimization strategies, and passive income analytics.',
    longDescription: 'Comprehensive wealth dashboard connecting multi-asset accounts, dividend tracking, and net worth forecasting tools.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'Plaid API', 'Recharts', 'PostgreSQL'],
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },

  // Image 2
  {
    title: 'Decision Studio',
    description: 'Multi-criteria decision analysis engine leveraging weighted matrix modeling and AI risk simulation for strategic choices.',
    longDescription: 'Decision science application helping leadership teams rank business strategies through automated risk scenarios.',
    category: 'AI & ML',
    tags: ['Python', 'FastAPI', 'React', 'TypeScript', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Threat Console Security Dashboard',
    description: 'Cybersecurity incident response console monitoring network logs, intrusion attempts, malware signatures, and IP threat scores.',
    longDescription: 'Real-time SOC security dashboard capturing network anomalies, unauthorized logins, and firewall events.',
    category: 'Backend & Cloud',
    tags: ['React', 'Node.js', 'Elasticsearch', 'Docker', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart Campus Operating Platform',
    description: 'Digital university ecosystem managing student attendance, library access, classroom scheduling, and campus event feeds.',
    longDescription: 'Unified higher education platform connecting students, faculty, and administrative staff across campus facilities.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'MongoDB', 'Tailwind CSS', 'Express'],
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Agro Vision Analytics',
    description: 'Satellite & drone crop health monitoring using computer vision multispectral indices to detect plant disease and predict harvest yield.',
    longDescription: 'Precision agriculture suite processing aerial multispectral imagery to evaluate soil hydration, pest threats, and yield targets.',
    category: 'AI & ML',
    tags: ['Python', 'PyTorch', 'OpenCV', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Personal Finance & Visual Budget Splitter',
    description: 'Interactive visual monthly expense breakdown tool with envelope budgeting, subscription tracking, and saving goal progress bars.',
    longDescription: 'Personal budget optimizer helping users visualize monthly cash flows and automate savings allocations.',
    category: 'Web',
    tags: ['React', 'Tailwind CSS', 'Framer Motion', 'Chart.js', 'LocalStorage'],
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Autonomous Personal Assistant',
    description: 'Voice & text intelligent agent executing calendar scheduling, email drafting, search summaries, and local device automation tasks.',
    longDescription: 'AI virtual assistant performing desktop workflows, document summarization, and hands-free voice operations.',
    category: 'AI & ML',
    tags: ['Python', 'OpenAI API', 'SpeechRecognition', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Autonomous Multi-Agent System',
    description: 'Collaborative AI agent network where specialized planner, researcher, coder, and reviewer agents solve complex tasks autonomously.',
    category: 'AI & ML',
    tags: ['Python', 'LangChain', 'CrewAI', 'FastAPI', 'Next.js'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'AI Subscription Leak Detector',
    description: 'Automated bank statement analyzer identifying hidden recurring SaaS charges, price increases, and unused subscriptions.',
    category: 'AI & ML',
    tags: ['React', 'Node.js', 'OpenAI API', 'Plaid API', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Phishing Detection System',
    description: 'Real-time URL and email header analyzer detecting deceptive domains, spoofing attempts, and malicious landing pages using ML rules.',
    category: 'AI & ML',
    tags: ['Python', 'Scikit-learn', 'Flask', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'PhonePe Payment Gateway Clone',
    description: 'Full-featured fintech app clone supporting instant UPI payments, QR scanning, wallet transfers, transaction history, and bill pay.',
    category: 'Full Stack',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1556742049-0a6745585b9b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'ChatGPT Assistant Clone',
    description: 'High-performance AI chat interface supporting code syntax highlighting, markdown rendering, thread history, and system prompts.',
    category: 'AI & ML',
    tags: ['Next.js', 'TypeScript', 'OpenAI API', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Meesho E-Commerce Platform',
    description: 'Social e-commerce marketplace clone enabling seller storefront creation, product sharing, order management, and commission tracking.',
    category: 'Web',
    tags: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Zomato Food Delivery Clone',
    description: 'Hyperlocal food ordering platform featuring restaurant discovery, menu customization, live GPS order tracking, and review system.',
    category: 'Full Stack',
    tags: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Train Booking System',
    description: 'Railway seat availability check, PNR status verification, route map inspection, and automated e-ticket issuance booking portal.',
    category: 'Web',
    tags: ['React', 'TypeScript', 'Node.js', 'Express', 'MySQL'],
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Rental & PG Verification Platform',
    description: 'Tenant background verification, owner agreement generation, PG room discovery, and rent payment escrow platform.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'PostgreSQL', 'Tailwind CSS', 'AWS S3'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart City Civic Complaint Management',
    description: 'Citizen grievance portal with geo-tagged photo uploads, automated department routing, and SLA escalation tracking.',
    category: 'Full Stack',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart Government Welfare Assistant',
    description: 'AI portal checking citizen eligibility for government welfare schemes, pension programs, and grant applications in regional languages.',
    category: 'AI & ML',
    tags: ['Next.js', 'Python', 'OpenAI API', 'Tailwind CSS', 'FastAPI'],
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Emergency Hospital Finder',
    description: 'Real-time ICU bed availability, blood bank stock levels, ambulance dispatch, and nearest trauma center locator.',
    category: 'Web',
    tags: ['React', 'Leaflet', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Digital Health Identity Vault',
    description: 'Encrypted personal medical record locker supporting doctor access sharing, prescription storage, and lab report history.',
    category: 'Backend & Cloud',
    tags: ['React', 'Node.js', 'CryptoJS', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart Digital Business Suite',
    description: 'SME operational suite combining digital invoicing, GST tax compliance, customer analytics, and inventory management.',
    category: 'Web',
    tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Prisma', 'PostgreSQL'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },

  // Image 3
  {
    title: 'Education & Learning Portal',
    description: 'Interactive e-learning LMS featuring video courses, quiz assignments, progress tracking, and peer discussion forums.',
    category: 'Web',
    tags: ['React', 'Next.js', 'Tailwind CSS', 'Node.js', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Full Stack App Suite',
    description: 'Modular enterprise codebase boilerplate with RBAC authentication, dark/light theme, API rate limiting, and Stripe billing.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart Rural Education Platform',
    description: 'Low-bandwidth digital learning hub enabling offline content caching, localized audio lessons, and rural school tracking.',
    category: 'Web',
    tags: ['React', 'PWA', 'Workbox', 'Tailwind CSS', 'IndexedDB'],
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Digital Safety System',
    description: 'Personal safety SOS application triggerable via quick shortcut, sending live GPS telemetry and audio alerts to trusted contacts.',
    category: 'Web',
    tags: ['React', 'TypeScript', 'Geolocation API', 'Twilio', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1508873696983-2df515122519?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Scam Detection Engine',
    description: 'AI model identifying fraudulent SMS messages, phishing links, and deceptive caller patterns in real time.',
    category: 'AI & ML',
    tags: ['Python', 'Scikit-learn', 'FastAPI', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Document Assistant AI',
    description: 'RAG-powered PDF document search and chat system enabling instant semantic query answering over 500+ page manuals.',
    category: 'AI & ML',
    tags: ['Python', 'LangChain', 'OpenAI API', 'FAISS', 'Next.js'],
    image: 'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Market Intelligence & Price Prediction',
    description: 'Commodity & stock price trend forecasting platform utilizing historical time series data and LSTM neural networks.',
    category: 'AI & ML',
    tags: ['Python', 'TensorFlow', 'Pandas', 'Flask', 'Chart.js'],
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Water Management System',
    description: 'IoT telemetry portal tracking reservoir water levels, pipeline leakage detection, flow rate analysis, and consumption quotas.',
    category: 'Backend & Cloud',
    tags: ['Node.js', 'Express', 'MongoDB', 'IoT Sensors', 'React'],
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart Navigation & Accessibility Hub',
    description: 'Voice-guided indoor & outdoor navigation app specifically designed to assist visually impaired individuals.',
    category: 'AI & ML',
    tags: ['React', 'TypeScript', 'Web Speech API', 'Mapbox', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Movie Recommendation Engine',
    description: 'Collaborative filtering and content-based recommendation system parsing user preferences to suggest tailored film lists.',
    category: 'AI & ML',
    tags: ['Python', 'Scikit-learn', 'TMDB API', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Online File Storage Platform',
    description: 'Cloud storage drive supporting file uploading, folder creation, link sharing, preview rendering, and storage metrics.',
    category: 'Backend & Cloud',
    tags: ['React', 'Node.js', 'AWS S3', 'Express', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Museum Guide Application',
    description: 'Interactive exhibit guide featuring AR artifact scanning, audio narrative playback, and exhibit map routing.',
    category: 'Web',
    tags: ['React', 'Three.js', 'Tailwind CSS', 'Framer Motion', 'PWA'],
    image: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Story Writing AI Assistant',
    description: 'Creative writing workspace offering character generation, plot twist suggestions, and dialogue expansion using LLM prompts.',
    category: 'AI & ML',
    tags: ['Next.js', 'TypeScript', 'OpenAI API', 'Tailwind CSS', 'ProseMirror'],
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Online Voting System',
    description: 'Cryptographically verified online election portal ensuring voter anonymity, tamper-proof ballot counting, and audit logs.',
    category: 'Backend & Cloud',
    tags: ['Node.js', 'Express', 'CryptoJS', 'MongoDB', 'React'],
    image: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Stock Market Price Prediction',
    description: 'Financial indicator analytics app utilizing ARIMA and LSTM models to predict stock price movements and moving averages.',
    category: 'AI & ML',
    tags: ['Python', 'TensorFlow', 'Pandas', 'Yahoo Finance API', 'React'],
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'File Transfer System',
    description: 'Peer-to-peer WebRTC file transfer utility enabling instant browser-to-browser encrypted file transfers without cloud limits.',
    category: 'Web',
    tags: ['React', 'WebRTC', 'Socket.io', 'Tailwind CSS', 'TypeScript'],
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Phishing Website Detection',
    description: 'Browser extension and backend API analyzing DOM elements, SSL certificate data, and URL patterns to block scam sites.',
    category: 'AI & ML',
    tags: ['Python', 'FastAPI', 'Chrome Extension API', 'Scikit-learn'],
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Book Exchange Platform',
    description: 'Community book swapping platform allowing readers to list books, send trade requests, rate traders, and track parcel deliveries.',
    category: 'Web',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Resume Generator Pro',
    description: 'Interactive resume builder with live ATS formatting check, PDF export, multi-template selector, and section reordering.',
    category: 'Web',
    tags: ['React', 'Next.js', 'Tailwind CSS', 'jsPDF', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Portfolio Builder Studio',
    description: 'No-code web portfolio editor allowing developers to customize themes, import GitHub repositories, and publish live sites.',
    category: 'Web',
    tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Monaco Editor', 'Vercel API'],
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Fake News Detection System',
    description: 'NLP classifier scoring news articles for credibility, bias, and clickbait indicators using BERT transformers.',
    category: 'AI & ML',
    tags: ['Python', 'PyTorch', 'Transformers', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },

  // Image 4
  {
    title: 'Online Book Store',
    description: 'Digital bookstore with instant book previews, e-reader mode, genre browsing, cart checkout, and reader reviews.',
    category: 'Web',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Grocery Delivery Platform',
    description: 'Instant grocery store delivery platform featuring inventory stock tracking, delivery slots, and real-time rider tracking.',
    category: 'Full Stack',
    tags: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'LinkedIn Network Clone',
    description: 'Professional networking platform clone supporting connection requests, feed posts, job listings, and message threads.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1611944212129-29977ae1398c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Instagram Social Media Clone',
    description: 'Photo & video sharing social platform featuring stories, posts, likes, comment threads, direct messages, and filters.',
    category: 'Full Stack',
    tags: ['React', 'Next.js', 'Firebase', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1611262588024-d12430b98920?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'WhatsApp Chat Clone',
    description: 'Real-time end-to-end encrypted chat web app with status updates, voice notes, media sharing, and group chats.',
    category: 'Full Stack',
    tags: ['React', 'Socket.io', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1614680376593-902f749f7b9e?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Student Portal',
    description: 'Academic student hub for tracking course schedules, exam grades, attendance percentages, and fee payment receipts.',
    category: 'Web',
    tags: ['React', 'TypeScript', 'Node.js', 'MySQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Netflix Advance Platform',
    description: 'Feature-rich movie streaming platform with trailer auto-play, category carousels, watchlists, and user profiles.',
    category: 'Web',
    tags: ['React', 'Next.js', 'TMDB API', 'Tailwind CSS', 'Firebase'],
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Quiz & Online Examination Platform',
    description: 'Secure timed online assessment system featuring anti-cheating tab switch alerts, auto-grading, and leaderboard stats.',
    category: 'Full Stack',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Multiplayer Quiz Game',
    description: 'Real-time competitive multiplayer trivia game with WebSockets lobbies, live scores, countdown timers, and streak bonuses.',
    category: 'Web',
    tags: ['React', 'Socket.io', 'Node.js', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Online Chess Game',
    description: 'Interactive web chess application supporting player vs player WebSockets matches, AI bot difficulty levels, and move history.',
    category: 'Web',
    tags: ['React', 'Chess.js', 'Stockfish API', 'Socket.io', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Warehouse Management System',
    description: 'Inventory tracking, barcode scanning integration, bin allocation, stock replenishment alerts, and logistics dispatch management.',
    category: 'Backend & Cloud',
    tags: ['React', 'Node.js', 'Express', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Safety & Parent Collaboration Platform',
    description: 'School bus tracking, student attendance notifications, parent-teacher messaging, and emergency broadcast channel.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'Firebase', 'Tailwind CSS', 'Twilio'],
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Administration Automation Platform',
    description: 'Automated administrative workflow system digitizing leave approvals, asset allocation, payroll vouchers, and document sign-offs.',
    category: 'Backend & Cloud',
    tags: ['Node.js', 'Express', 'MongoDB', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'School Fee Management System',
    description: 'Automated student fee collection portal with online payment gateways, installment receipts, late fee rules, and accounting ledger.',
    category: 'Web',
    tags: ['React', 'Node.js', 'Express', 'MySQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart School Operating System',
    description: 'Complete K-12 school administration platform covering timetable creation, gradebooks, exam results, and parent communication.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'MongoDB', 'Tailwind CSS', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Regional Language AI Engine',
    description: 'Multilingual neural translation and text-to-speech model supporting Indic regional languages for digital accessibility.',
    category: 'AI & ML',
    tags: ['Python', 'PyTorch', 'Transformers', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Smart Public Transport System',
    description: 'Real-time city bus & metro location tracking, arrival estimations, ticketing QR codes, and crowding statistics.',
    category: 'Full Stack',
    tags: ['React', 'Leaflet', 'Node.js', 'WebSockets', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'FinReach AI',
    description: 'AI-driven microfinance credit scoring engine evaluating alternative data points for underbanked entrepreneurs.',
    category: 'AI & ML',
    tags: ['Python', 'XGBoost', 'Scikit-learn', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Hotel Booking Engine',
    description: 'Fast hotel reservation portal with filterable amenities, room photos, reviews, instant confirmation, and map views.',
    category: 'Web',
    tags: ['React', 'Next.js', 'Tailwind CSS', 'Node.js', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Movie Ticket Booking System',
    description: 'Cinema seat selection layout, showtime schedule browser, food counter pre-orders, and e-ticket QR generation.',
    category: 'Web',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Flight Booking Portal',
    description: 'Airline flight search comparison, fare class selection, seat map reservation, baggage add-ons, and boarding passes.',
    category: 'Full Stack',
    tags: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },

  // Image 5
  {
    title: 'Food Delivery System',
    description: 'Full food ordering flow with interactive restaurant menus, dish search, live delivery map, and driver updates.',
    category: 'Full Stack',
    tags: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Digital Banking Platform',
    description: 'Modern online banking experience with account statements, fund transfers, virtual debit cards, and loan applications.',
    category: 'Full Stack',
    tags: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Doctor Appointment Booking',
    description: 'Healthcare portal allowing patients to search specialists, book clinic time slots, upload medical records, and pay online.',
    category: 'Web',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Car Rental Management System',
    description: 'Fleet management and rental booking application handling vehicle availability, driver ID checks, and rental contracts.',
    category: 'Full Stack',
    tags: ['React', 'TypeScript', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Travel Planner & Smart Tourism Platform',
    description: 'AI-assisted itinerary planner generating custom travel routes, hotel suggestions, attraction bookings, and budget estimates.',
    category: 'AI & ML',
    tags: ['Next.js', 'TypeScript', 'OpenAI API', 'Tailwind CSS', 'Mapbox'],
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Property Management System',
    description: 'Real estate portfolio management system tracking tenant leases, maintenance maintenance tickets, and rental income.',
    category: 'Full Stack',
    tags: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'House Rental & Property Finder',
    description: 'Property search portal with interactive map boundaries, virtual 360 tours, owner contact forms, and filterable amenities.',
    category: 'Web',
    tags: ['React', 'Next.js', 'Tailwind CSS', 'Leaflet', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Gaming Platform Hub',
    description: 'Online web gaming hub hosting browser games, global score leaderboards, player profiles, and tournament brackets.',
    category: 'Web',
    tags: ['React', 'PhaserJS', 'Socket.io', 'Tailwind CSS', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Netflix Streaming Hub',
    description: 'High-performance video streaming platform UI with custom video player controls, subtitle support, and watch list.',
    category: 'Web',
    tags: ['React', 'Next.js', 'Tailwind CSS', 'Video.js', 'Firebase'],
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Spotify Music Player Clone',
    description: 'Web audio player with custom playlists, interactive audio equalizer, lyrics sync, artist search, and volume controls.',
    category: 'Web',
    tags: ['React', 'Next.js', 'Web Audio API', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Mall Management System',
    description: 'Shopping mall store directory, indoor kiosk navigation, promotional offer wall, and parking space reservation portal.',
    category: 'Web',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'Weather App & Forecast Hub',
    description: 'Interactive weather web app rendering 7-day hourly forecasts, UV index, radar maps, and weather alerts via OpenWeather API.',
    category: 'Web',
    tags: ['React', 'TypeScript', 'OpenWeather API', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'College Management System',
    description: 'Comprehensive college portal managing faculty rosters, department courses, student enrollment, and examination marks.',
    category: 'Full Stack',
    tags: ['React', 'TypeScript', 'Node.js', 'MySQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    title: 'AI Chatbot Assistant',
    description: 'Embeddable intelligent customer support chatbot trained on custom knowledge bases for automated ticket resolution.',
    category: 'AI & ML',
    tags: ['Python', 'FastAPI', 'OpenAI API', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
];

export async function GET() {
  try {
    const db = await connectToDatabase();
    if (!db) {
      return NextResponse.json(INITIAL_PROJECTS, { status: 200 });
    }

    let projects = await Project.find().sort({ createdAt: -1 }).lean();

    // Auto-seed or update if database has incomplete project list
    if (projects.length < INITIAL_PROJECTS.length) {
      await Project.deleteMany({});
      await Project.insertMany(INITIAL_PROJECTS);
      projects = await Project.find().sort({ createdAt: -1 }).lean();
    }

    return NextResponse.json(projects, { status: 200 });
  } catch (error) {
    console.error('Error fetching projects:', error);
    return NextResponse.json(INITIAL_PROJECTS, { status: 200 });
  }
}

export async function POST(request: Request) {
  if (!verifyAdminToken(request)) {
    return NextResponse.json({ message: 'Unauthorized access.' }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { title, description, longDescription, category, image, tags, liveUrl, githubUrl, featured } = body;

    if (!title || !description || !image) {
      return NextResponse.json(
        { message: 'Title, description, and image URL are required.' },
        { status: 400 }
      );
    }

    await connectToDatabase();
    const newProject = await Project.create({
      title,
      description,
      longDescription: longDescription || description,
      category: category || 'Full Stack',
      image,
      tags: Array.isArray(tags) ? tags : (tags || '').split(',').map((t: string) => t.trim()),
      liveUrl: liveUrl || '#',
      githubUrl: githubUrl || '#',
      featured: Boolean(featured),
    });

    return NextResponse.json({ success: true, project: newProject }, { status: 201 });
  } catch (error) {
    console.error('Error creating project:', error);
    return NextResponse.json({ message: 'Failed to create project' }, { status: 500 });
  }
}
