import {
  HighlightStat,
  Skill,
  Project,
  ExperienceItem,
  EducationItem,
  CertificateItem,
  ServiceItem,
  TestimonialItem,
  NavItem,
} from '@/types/portfolio';

export const PERSONAL_INFO = {
  name: 'Krishna Devadkar',
  role: 'Full Stack Developer & AI Engineer',
  roles: [
    'Full Stack Developer',
    'AI Engineer',
    'Python Developer',
    'React Developer',
    'Backend Developer',
  ],
  bio: `Passionate Senior Full Stack Developer and AI Engineer dedicated to building high-performance, scalable web applications and intelligent AI solutions. Experienced in architecting production-ready cloud architectures, training machine learning models, and crafting pixel-perfect, interactive user interfaces with modern web standards.`,
  longBio: `I craft digital products that seamlessly bridge user-centric design with advanced backend intelligence. With expertise spanning Next.js, React, Python, Node.js, and Machine Learning algorithms, I turn complex ideas into elegant, reliable applications. Always striving for clean code, high speed, accessibility, and exceptional visual design reminiscent of Stripe, Vercel, and Linear.`,
  location: 'Kolhapur, India',
  email: 'krishnadevadkar@gmail.com',
  phone: '+91 82088 63439',
  github: 'https://github.com/Krishna8208863439',
  linkedin: 'https://linkedin.com/in/krishna-devadkar',
  instagram: 'https://instagram.com/krishna.dev',
  twitter: 'https://x.com/krishna_dev',
  workingHours: 'Mon - Sat: 9:00 AM - 8:00 PM IST',
  availableForHire: true,
};

export const NAV_ITEMS: NavItem[] = [
  { name: 'Home', href: '#home' },
  { name: 'About', href: '#about' },
  { name: 'Skills', href: '#skills' },
  { name: 'Projects', href: '#projects' },
  { name: 'Resume', href: '#resume' },
  { name: 'Contact', href: '#contact' },
];

export const HIGHLIGHT_STATS: HighlightStat[] = [
  {
    label: 'Years Learning & Building',
    value: 4,
    suffix: '+',
    description: 'Continuous growth, active coding & system architecture',
    iconName: 'Code',
  },
  {
    label: 'Projects Completed',
    value: 90,
    suffix: '+',
    description: 'Full stack web apps, AI models & production microservices',
    iconName: 'FolderCheck',
  },
  {
    label: 'Core Technologies',
    value: 15,
    suffix: '+',
    description: 'Frontend, Backend, AI frameworks & Cloud DevOps tools',
    iconName: 'Cpu',
  },
  {
    label: 'Certifications & Honors',
    value: 10,
    suffix: '+',
    description: 'AWS, TensorFlow, Google & Hackathon Top Awards',
    iconName: 'Award',
  },
];

export const SKILLS_DATA: Skill[] = [
  // Frontend
  { name: 'HTML5', category: 'Frontend', level: 95, iconName: 'FileCode' },
  { name: 'CSS3', category: 'Frontend', level: 92, iconName: 'Palette' },
  { name: 'JavaScript', category: 'Frontend', level: 95, iconName: 'Zap', popular: true },
  { name: 'TypeScript', category: 'Frontend', level: 92, iconName: 'ShieldCheck', popular: true },
  { name: 'React', category: 'Frontend', level: 94, iconName: 'Atom', popular: true },
  { name: 'Next.js', category: 'Frontend', level: 92, iconName: 'Layers', popular: true },
  { name: 'Tailwind CSS', category: 'Frontend', level: 95, iconName: 'Wind', popular: true },

  // Backend
  { name: 'Node.js', category: 'Backend', level: 90, iconName: 'Server', popular: true },
  { name: 'Express.js', category: 'Backend', level: 88, iconName: 'Workflow' },
  { name: 'Python', category: 'Backend', level: 92, iconName: 'Terminal', popular: true },
  { name: 'Flask', category: 'Backend', level: 85, iconName: 'Flame' },
  { name: 'FastAPI', category: 'Backend', level: 88, iconName: 'Cpu' },

  // Database
  { name: 'MongoDB', category: 'Database', level: 88, iconName: 'Database', popular: true },
  { name: 'PostgreSQL', category: 'Database', level: 86, iconName: 'HardDrive' },
  { name: 'MySQL', category: 'Database', level: 84, iconName: 'Table' },
  { name: 'Firebase', category: 'Database', level: 85, iconName: 'Flame' },

  // AI & ML
  { name: 'TensorFlow', category: 'AI', level: 85, iconName: 'BrainCircuit', popular: true },
  { name: 'PyTorch', category: 'AI', level: 82, iconName: 'Sparkles' },
  { name: 'OpenCV', category: 'AI', level: 84, iconName: 'Eye' },
  { name: 'Machine Learning', category: 'AI', level: 88, iconName: 'Activity', popular: true },
  { name: 'Deep Learning', category: 'AI', level: 85, iconName: 'Network' },

  // Cloud & DevOps
  { name: 'AWS', category: 'Cloud', level: 84, iconName: 'Cloud', popular: true },
  { name: 'Vercel', category: 'Cloud', level: 94, iconName: 'Triangle' },
  { name: 'Netlify', category: 'Cloud', level: 90, iconName: 'Globe' },
  { name: 'Docker', category: 'Cloud', level: 82, iconName: 'Box', popular: true },

  // Tools
  { name: 'Git', category: 'Tools', level: 92, iconName: 'GitBranch' },
  { name: 'GitHub', category: 'Tools', level: 94, iconName: 'Github' },
  { name: 'VS Code', category: 'Tools', level: 96, iconName: 'Code2' },
  { name: 'Postman', category: 'Tools', level: 90, iconName: 'Send' },
  { name: 'Figma', category: 'Tools', level: 86, iconName: 'Figma' },
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 'proj-smart-kisan',
    title: 'Smart Kisan AI – Agritech Platform',
    subtitle: 'AI crop yield recommendation, plant disease diagnosis & live market prices',
    description: 'AI-driven smart agriculture platform providing crop recommendation, plant leaf disease detection using computer vision, real-time market price predictions, soil telemetry, and an AI farming assistant.',
    longDescription: 'Comprehensive agritech ecosystem helping farmers optimize crop yields, detect crop diseases using deep neural networks, monitor soil metrics, track live mandi prices, and consult an AI agronomist.',
    category: 'AI',
    technologies: ['Python', 'Flask', 'FastAPI', 'TensorFlow', 'OpenCV', 'React', 'Node.js', 'Tailwind CSS', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439/Smart-Kisan-Final',
    liveUrl: 'https://github.com/Krishna8208863439/Smart-Kisan-Final',
    featured: true,
  },
  {
    id: 'proj-coderush',
    title: 'CodeRush 2.0 – Competitive Coding Platform',
    subtitle: 'Real-time coding contest & isolated execution sandbox',
    description: 'Real-time competitive programming platform built for CodeWarriors hackathon, featuring instant code execution sandbox, algorithmic problem sets, automated scoring, and live leaderboards.',
    longDescription: 'Full stack developer contest platform with multi-language code runner sandbox, real-time scoreboard via WebSockets, and automated test suite verification.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'Node.js', 'Docker Sandbox', 'WebSockets', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-medical-chatbot',
    title: 'End-to-End AI Medical Chatbot',
    subtitle: 'RAG-powered health assistant for medical triage & symptom diagnosis',
    description: 'RAG-powered conversational medical chatbot trained on healthcare datasets for symptom evaluation, medical triage guidance, and prescription information.',
    longDescription: 'AI healthcare assistant utilizing Retrieval-Augmented Generation (RAG) and vector databases to parse clinical medical manuals, provide instant symptom advice, and answer medical queries.',
    category: 'AI',
    technologies: ['Python', 'LangChain', 'Pinecone', 'OpenAI API', 'Flask', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-smart-healthcare',
    title: 'Smart Healthcare Diagnostics System',
    subtitle: 'Unified digital medical portal & patient telemetry',
    description: 'Comprehensive medical diagnostics and hospital portal connecting patient EMR records, virtual doctor consultations, lab report analysis, and disease risk scoring.',
    longDescription: 'End-to-end healthcare web platform featuring electronic medical records (EMR), live doctor booking, AI diagnostic risk scoring, and secure medical data vaulting.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Python', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-snake-ai',
    title: 'Snake Game with AI Twist',
    subtitle: 'Reinforcement Learning & AI-powered arcade game',
    description: 'Interactive modern arcade Snake game enhanced with Reinforcement Learning (Q-learning AI mode), adaptive difficulty obstacles, and dynamic visual themes.',
    longDescription: 'Browser arcade game combining classic gameplay with autonomous AI bot mode powered by Q-learning algorithms and dynamic pathfinding.',
    category: 'AI',
    technologies: ['JavaScript', 'TypeScript', 'Python', 'Pygame', 'HTML5 Canvas', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-sagecommand',
    title: 'SageCommand AI Production Hub',
    subtitle: 'Autonomous AI command console & workflow orchestrator',
    description: 'Enterprise-grade autonomous AI command console orchestrating LLM agent workflows, automated prompt chains, script execution, and cloud telemetry monitoring.',
    longDescription: 'Production-ready AI command center enabling enterprise teams to trigger multi-agent task pipelines, monitor LLM API usage, and inspect autonomous logs.',
    category: 'AI',
    technologies: ['Python', 'FastAPI', 'React', 'Docker', 'Tailwind CSS', 'LangChain'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-ai-agent',
    title: 'Autonomous Multi-Agent Workspace',
    subtitle: 'Multi-agent collaboration engine & browser automation',
    description: 'Autonomous task execution framework where specialized planner, browser researcher, code builder, and reviewer AI agents collaborate to fulfill complex developer goals.',
    longDescription: 'Autonomous multi-agent system coordinating specialized AI subagents with tool execution, browser automation, web search, and code synthesis.',
    category: 'AI',
    technologies: ['Python', 'LangChain', 'CrewAI', 'FastAPI', 'React', 'Next.js'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-online-exam',
    title: 'Online Examination & Assessment Portal',
    subtitle: 'Proctored online exam platform with anti-cheat detection',
    description: 'Proctored digital examination portal featuring tab-switch anti-cheating alerts, timed question sets, automated instant grading, and detailed performance analytics.',
    longDescription: 'Educational assessment engine enforcing strict proctoring rules, randomized question shuffling, instant score calculation, and student analytics.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-bangalore-transport',
    title: 'Bangalore Smart Transport Network',
    subtitle: 'Metropolitan bus/metro live tracking & QR ticketing',
    description: 'Intelligent urban transport platform for metropolitan route planning, live bus and metro GPS telemetry, digital QR ticketing, and transit crowding analytics.',
    longDescription: 'City transport tracking hub providing commuters with live bus locations, estimated arrival times, digital QR passes, and traffic congestion feeds.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'Leaflet', 'WebSockets', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-pune-civic',
    title: 'Pune Civic & Grievance Portal',
    subtitle: 'Geo-tagged municipal complaint & public service hub',
    description: 'Smart city civic application for citizen grievance reporting, geo-tagged photo uploads, department SLA tracking, emergency alerts, and municipal updates.',
    longDescription: 'Municipal civic engagement platform connecting citizens with urban governance for quick resolution of infrastructure issues and public complaints.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-smart-mall',
    title: 'Smart Mall Management Portal',
    subtitle: 'Store directory kiosk & parking reservation hub',
    description: 'Shopping mall directory platform featuring interactive store maps, promotional deals showcase, customer feedback, and automated parking spot reservations.',
    longDescription: 'Digital shopping mall application providing store location maps, promotional deal banners, interactive store cataloging, and real-time parking slot bookings.',
    category: 'Web',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  // Image 1
  {
    id: 'proj-1',
    title: 'Waste Management System',
    subtitle: 'Smart IoT & AI-driven municipal waste tracking',
    description: 'Smart IoT & AI-driven municipal waste tracking, bin capacity sensor monitoring, and automated garbage collection route optimization.',
    longDescription: 'End-to-end municipal waste tracking system using sensor telemetry and AI route planning to minimize fuel usage and eliminate overflow bins.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'IoT Sensors', 'MongoDB', 'Express'],
    image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-2',
    title: 'Smart City Operating System',
    subtitle: 'Centralized urban management platform',
    description: 'Centralized urban management platform visualizing traffic telemetry, energy grid status, emergency dispatch, and environmental sensor data.',
    longDescription: 'Interactive command dashboard giving city controllers real-time metrics across public transit, power grids, emergency services, and air quality.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'WebSockets', 'Tailwind CSS', 'Recharts'],
    image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-3',
    title: 'E-Commerce Analytics Hub',
    subtitle: 'Real-time sales performance & customer LTV forecasting',
    description: 'Real-time sales performance, customer LTV forecasting, conversion funnel tracking, and inventory telemetry dashboard.',
    longDescription: 'High-conversion analytics engine analyzing sales funnels, cart abandonment rates, and revenue projections.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'PostgreSQL', 'Chart.js'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-4',
    title: 'Shade Match Studio',
    subtitle: 'AI computer vision cosmetic foundation analyzer',
    description: 'AI computer vision application analyzing user facial photos under ambient light to recommend exact cosmetic foundation shades.',
    longDescription: 'Computer vision shade analyzer fine-tuned on diverse skin tone datasets to deliver accurate cosmetic color matching.',
    category: 'AI',
    technologies: ['Python', 'OpenCV', 'TensorFlow', 'React', 'FastAPI'],
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-5',
    title: 'Crisis Response Center',
    subtitle: 'Emergency disaster response coordination platform',
    description: 'Emergency disaster response coordination platform mapping incidents, resource distribution, and real-time survivor SOS alerts.',
    longDescription: 'Disaster management hub connecting first responders, relief centers, and affected citizens with live map routing.',
    category: 'Full Stack',
    technologies: ['Next.js', 'Leaflet', 'Node.js', 'WebSockets', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-6',
    title: 'Gallery App',
    subtitle: 'Cloud image vault with automated AI tagging',
    description: 'High-speed cloud image vault with automated AI auto-tagging, face grouping, spatial search, and seamless drag-and-drop uploads.',
    longDescription: 'Personal photo management suite using deep neural networks to automatically index and search photo collections.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'Cloudinary', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-7',
    title: 'Library Management System',
    subtitle: 'Digital cataloging & RFID borrowing administration',
    description: 'Digital cataloging, RFID book issuance, fine tracking, automated reminder dispatch, and reader borrowing telemetry.',
    longDescription: 'Automated library administration portal tracking physical books, digital loans, reader memberships, and return schedules.',
    category: 'Full Stack',
    technologies: ['Node.js', 'Express', 'MySQL', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-8',
    title: 'Restaurant Billing System',
    subtitle: 'Touch POS & kitchen display system',
    description: 'POS point-of-sale touch system featuring kitchen display routing, table QR ordering, digital receipts, and inventory deductions.',
    longDescription: 'High-speed restaurant billing software streamlining kitchen communication, customer table orders, and daily revenue reports.',
    category: 'Full Stack',
    technologies: ['React', 'Electron', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-9',
    title: 'Password Manager Vault',
    subtitle: 'Zero-knowledge AES-256 encrypted credential vault',
    description: 'Zero-knowledge AES-256 encrypted credential vault with master key derivative hashing, breach alerts, and 2FA generator.',
    longDescription: 'Secure password locker utilizing local client encryption before sync, preventing unauthorized data breaches.',
    category: 'Web',
    technologies: ['React', 'TypeScript', 'CryptoJS', 'Node.js', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-10',
    title: 'Hotel Booking Management System',
    subtitle: 'Property reservation platform with dynamic pricing',
    description: 'Comprehensive property reservation platform with dynamic room pricing, seasonal availability calendars, and payment gateway.',
    longDescription: 'Full hotel operations management tool handling online bookings, room cleaning status, guest check-ins, and billing.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'Stripe', 'PostgreSQL', 'Prisma'],
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-11',
    title: 'Startup Empire Simulator',
    subtitle: 'Gamified startup economics & strategy simulator',
    description: 'Gamified business simulation web app modeling venture capital funding, product development cycles, and customer acquisition curves.',
    longDescription: 'Interactive strategy web game modeling startup economics, engineering hires, marketing campaigns, and investor pitches.',
    category: 'Web',
    technologies: ['React', 'TypeScript', 'Canvas API', 'Tailwind CSS', 'Zustand'],
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-12',
    title: 'Intelligence Investigation Board',
    subtitle: 'Interactive node graph visualization board',
    description: 'Interactive node graph visualization board for law enforcement data link analysis, suspect connections, and timeline evidence.',
    longDescription: 'Graph network analytics application connecting complex case evidence, financial transactions, and suspect communication channels.',
    category: 'AI',
    technologies: ['React', 'Cytoscape.js', 'Python', 'FastAPI', 'Neo4j'],
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-13',
    title: 'Founder Operating System',
    subtitle: 'All-in-one workspace for startup founders',
    description: 'All-in-one founder workspace managing investor CRM, runway calculation, KPI metrics, task execution, and team delegation.',
    longDescription: 'Central command portal for startup founders tracking burn rates, cap tables, key metrics, and team milestones.',
    category: 'Web',
    technologies: ['Next.js', 'React', 'Tailwind CSS', 'Supabase', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-14',
    title: 'Relationship Intelligence CRM',
    subtitle: 'AI customer relationship & outreach predictor',
    description: 'AI-assisted customer contact relationship manager predicting outreach timing, sentiment analysis, and relationship health scores.',
    longDescription: 'Smart CRM analyzing interaction frequency and conversation tone to score customer satisfaction and retention likelihood.',
    category: 'AI',
    technologies: ['React', 'Node.js', 'OpenAI API', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-15',
    title: 'Wealth DNA Financial Hub',
    subtitle: 'Personalized multi-asset wealth building platform',
    description: 'Personalized wealth building platform aggregating investments, crypto portfolios, tax optimization strategies, and passive income analytics.',
    longDescription: 'Comprehensive wealth dashboard connecting multi-asset accounts, dividend tracking, and net worth forecasting tools.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'Plaid API', 'Recharts', 'PostgreSQL'],
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },

  // Image 2
  {
    id: 'proj-16',
    title: 'Decision Studio',
    subtitle: 'Multi-criteria decision science & risk engine',
    description: 'Multi-criteria decision analysis engine leveraging weighted matrix modeling and AI risk simulation for strategic choices.',
    longDescription: 'Decision science application helping leadership teams rank business strategies through automated risk scenarios.',
    category: 'AI',
    technologies: ['Python', 'FastAPI', 'React', 'TypeScript', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-17',
    title: 'Threat Console Security Dashboard',
    subtitle: 'Cybersecurity incident & network threat console',
    description: 'Cybersecurity incident response console monitoring network logs, intrusion attempts, malware signatures, and IP threat scores.',
    longDescription: 'Real-time SOC security dashboard capturing network anomalies, unauthorized logins, and firewall events.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'Elasticsearch', 'Docker', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-18',
    title: 'Smart Campus Operating Platform',
    subtitle: 'Digital university ecosystem & student portal',
    description: 'Digital university ecosystem managing student attendance, library access, classroom scheduling, and campus event feeds.',
    longDescription: 'Unified higher education platform connecting students, faculty, and administrative staff across campus facilities.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'MongoDB', 'Tailwind CSS', 'Express'],
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-19',
    title: 'Agro Vision Analytics',
    subtitle: 'Multispectral computer vision crop health monitoring',
    description: 'Satellite & drone crop health monitoring using computer vision multispectral indices to detect plant disease and predict harvest yield.',
    longDescription: 'Precision agriculture suite processing aerial multispectral imagery to evaluate soil hydration, pest threats, and yield targets.',
    category: 'AI',
    technologies: ['Python', 'PyTorch', 'OpenCV', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-20',
    title: 'Personal Finance & Visual Budget Splitter',
    subtitle: 'Visual envelope budgeting & cash flow splitter',
    description: 'Interactive visual monthly expense breakdown tool with envelope budgeting, subscription tracking, and saving goal progress bars.',
    longDescription: 'Personal budget optimizer helping users visualize monthly cash flows and automate savings allocations.',
    category: 'Web',
    technologies: ['React', 'Tailwind CSS', 'Framer Motion', 'Chart.js', 'LocalStorage'],
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-21',
    title: 'Autonomous Personal Assistant',
    subtitle: 'Voice & text intelligent automation agent',
    description: 'Voice & text intelligent agent executing calendar scheduling, email drafting, search summaries, and local device automation tasks.',
    longDescription: 'AI virtual assistant performing desktop workflows, document summarization, and hands-free voice operations.',
    category: 'AI',
    technologies: ['Python', 'OpenAI API', 'SpeechRecognition', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-22',
    title: 'Autonomous Multi-Agent System',
    subtitle: 'Collaborative AI multi-agent orchestration network',
    description: 'Collaborative AI agent network where specialized planner, researcher, coder, and reviewer agents solve complex tasks autonomously.',
    longDescription: 'Multi-agent orchestration framework coordinating autonomous specialized agents to deliver end-to-end task completion.',
    category: 'AI',
    technologies: ['Python', 'LangChain', 'CrewAI', 'FastAPI', 'Next.js'],
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-23',
    title: 'AI Subscription Leak Detector',
    subtitle: 'Automated bank statement SaaS charge analyzer',
    description: 'Automated bank statement analyzer identifying hidden recurring SaaS charges, price increases, and unused subscriptions.',
    longDescription: 'Smart financial tool analyzing connected bank accounts to flag recurring subscriptions and hidden trial fees.',
    category: 'AI',
    technologies: ['React', 'Node.js', 'OpenAI API', 'Plaid API', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-24',
    title: 'Phishing Detection System',
    description: 'Real-time URL and email header analyzer detecting deceptive domains, spoofing attempts, and malicious landing pages using ML rules.',
    longDescription: 'Machine learning security utility parsing domain metadata, SSL certificates, and text structure to identify cyber scams.',
    category: 'AI',
    technologies: ['Python', 'Scikit-learn', 'Flask', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-25',
    title: 'PhonePe Payment Gateway Clone',
    subtitle: 'UPI payment gateway & digital wallet clone',
    description: 'Full-featured fintech app clone supporting instant UPI payments, QR scanning, wallet transfers, transaction history, and bill pay.',
    longDescription: 'High-performance fintech portal providing seamless digital payment processing, wallet recharges, and bill settlements.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1556742049-0a6745585b9b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-26',
    title: 'ChatGPT Assistant Clone',
    subtitle: 'Conversational LLM workspace with code rendering',
    description: 'High-performance AI chat interface supporting code syntax highlighting, markdown rendering, thread history, and system prompts.',
    longDescription: 'Conversational AI workspace providing streaming responses, multi-model selection, and session history management.',
    category: 'AI',
    technologies: ['Next.js', 'TypeScript', 'OpenAI API', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-27',
    title: 'Meesho E-Commerce Platform',
    subtitle: 'Social reseller marketplace & order manager',
    description: 'Social e-commerce marketplace clone enabling seller storefront creation, product sharing, order management, and commission tracking.',
    longDescription: 'Social e-commerce storefront allowing independent sellers to catalog products and process customer orders.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-28',
    title: 'Zomato Food Delivery Clone',
    subtitle: 'Hyperlocal food ordering & live delivery tracker',
    description: 'Hyperlocal food ordering platform featuring restaurant discovery, menu customization, live GPS order tracking, and review system.',
    longDescription: 'On-demand food delivery portal connecting users with local restaurants, real-time map tracking, and reviews.',
    category: 'Full Stack',
    technologies: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-29',
    title: 'Train Booking System',
    subtitle: 'Railway PNR & seat reservation portal',
    description: 'Railway seat availability check, PNR status verification, route map inspection, and automated e-ticket issuance booking portal.',
    longDescription: 'Railway ticketing platform supporting live seat selection, route timetables, PNR checking, and instant e-tickets.',
    category: 'Web',
    technologies: ['React', 'TypeScript', 'Node.js', 'Express', 'MySQL'],
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-30',
    title: 'Rental & PG Verification Platform',
    subtitle: 'Tenant background verification & PG discovery',
    description: 'Tenant background verification, owner agreement generation, PG room discovery, and rent payment escrow platform.',
    longDescription: 'Housing rental ecosystem enabling verified PG listings, digital lease agreements, and secure rent transfers.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'PostgreSQL', 'Tailwind CSS', 'AWS S3'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-31',
    title: 'Smart City Civic Complaint Management',
    subtitle: 'Geo-tagged citizen grievance portal',
    description: 'Citizen grievance portal with geo-tagged photo uploads, automated department routing, and SLA escalation tracking.',
    longDescription: 'Public grievance portal connecting citizens with municipal departments to resolve infrastructure issues.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-32',
    title: 'Smart Government Welfare Assistant',
    subtitle: 'AI scheme eligibility checker in regional languages',
    description: 'AI portal checking citizen eligibility for government welfare schemes, pension programs, and grant applications in regional languages.',
    longDescription: 'Multilingual government assistant guiding citizens through welfare program requirements and document submissions.',
    category: 'AI',
    technologies: ['Next.js', 'Python', 'OpenAI API', 'Tailwind CSS', 'FastAPI'],
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-33',
    title: 'Emergency Hospital Finder',
    subtitle: 'Real-time ICU bed & trauma center locator',
    description: 'Real-time ICU bed availability, blood bank stock levels, ambulance dispatch, and nearest trauma center locator.',
    longDescription: 'Medical emergency app providing real-time ICU bed updates, blood availability, and instant ambulance dispatching.',
    category: 'Web',
    technologies: ['React', 'Leaflet', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-34',
    title: 'Digital Health Identity Vault',
    subtitle: 'Encrypted medical records & prescription vault',
    description: 'Encrypted personal medical record locker supporting doctor access sharing, prescription storage, and lab report history.',
    longDescription: 'Patient health locker ensuring private medical records can be securely shared with healthcare providers.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'CryptoJS', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-35',
    title: 'Smart Digital Business Suite',
    subtitle: 'SME invoicing, GST tax & inventory suite',
    description: 'SME operational suite combining digital invoicing, GST tax compliance, customer analytics, and inventory management.',
    longDescription: 'All-in-one business software handling GST invoicing, inventory tracking, and sales reporting for small enterprises.',
    category: 'Web',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Prisma', 'PostgreSQL'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },

  // Image 3
  {
    id: 'proj-36',
    title: 'Education & Learning Portal',
    subtitle: 'Interactive LMS platform with course tracking',
    description: 'Interactive e-learning LMS featuring video courses, quiz assignments, progress tracking, and peer discussion forums.',
    longDescription: 'Comprehensive learning management system supporting video streaming, interactive quizzes, and student gradebooks.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'Node.js', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-37',
    title: 'Full Stack App Suite',
    subtitle: 'Modular enterprise web application boilerplate',
    description: 'Modular enterprise codebase boilerplate with RBAC authentication, dark/light theme, API rate limiting, and Stripe billing.',
    longDescription: 'Production-ready full stack architecture with multi-tenant auth, role permissions, and integrated payments.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-38',
    title: 'Smart Rural Education Platform',
    subtitle: 'Low-bandwidth offline digital learning platform',
    description: 'Low-bandwidth digital learning hub enabling offline content caching, localized audio lessons, and rural school tracking.',
    longDescription: 'PWA educational tool engineered for low connectivity areas with offline caching and audio lessons.',
    category: 'Web',
    technologies: ['React', 'PWA', 'Workbox', 'Tailwind CSS', 'IndexedDB'],
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-39',
    title: 'Digital Safety System',
    subtitle: 'Personal emergency SOS & live GPS alert app',
    description: 'Personal safety SOS application triggerable via quick shortcut, sending live GPS telemetry and audio alerts to trusted contacts.',
    longDescription: 'Mobile safety portal offering quick shortcut emergency alerts, live GPS streaming, and panic notifications.',
    category: 'Web',
    technologies: ['React', 'TypeScript', 'Geolocation API', 'Twilio', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1508873696983-2df515122519?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-40',
    title: 'Scam Detection Engine',
    subtitle: 'AI fraudulent SMS & spam link identifier',
    description: 'AI model identifying fraudulent SMS messages, phishing links, and deceptive caller patterns in real time.',
    longDescription: 'Machine learning security model scoring incoming messages for fraud signals and known phishing patterns.',
    category: 'AI',
    technologies: ['Python', 'Scikit-learn', 'FastAPI', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-41',
    title: 'Document Assistant AI',
    subtitle: 'RAG semantic search & Q&A over PDF manuals',
    description: 'RAG-powered PDF document search and chat system enabling instant semantic query answering over 500+ page manuals.',
    longDescription: 'Vector search assistant indexing large technical documents for instant conversational Q&A.',
    category: 'AI',
    technologies: ['Python', 'LangChain', 'OpenAI API', 'FAISS', 'Next.js'],
    image: 'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-42',
    title: 'Market Intelligence & Price Prediction',
    subtitle: 'LSTM time series forecasting for commodity prices',
    description: 'Commodity & stock price trend forecasting platform utilizing historical time series data and LSTM neural networks.',
    longDescription: 'Neural network time series forecasting platform analyzing market trends to predict commodity prices.',
    category: 'AI',
    technologies: ['Python', 'TensorFlow', 'Pandas', 'Flask', 'Chart.js'],
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-43',
    title: 'Water Management System',
    subtitle: 'IoT telemetry & pipeline leak detection hub',
    description: 'IoT telemetry portal tracking reservoir water levels, pipeline leakage detection, flow rate analysis, and consumption quotas.',
    longDescription: 'IoT monitoring system providing water utility operators with real-time pressure, flow, and leak alerts.',
    category: 'Full Stack',
    technologies: ['Node.js', 'Express', 'MongoDB', 'IoT Sensors', 'React'],
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-44',
    title: 'Smart Navigation & Accessibility Hub',
    subtitle: 'Voice-guided navigation for visually impaired',
    description: 'Voice-guided indoor & outdoor navigation app specifically designed to assist visually impaired individuals.',
    longDescription: 'Accessible navigation assistant leveraging audio cues and haptic feedback for spatial guidance.',
    category: 'AI',
    technologies: ['React', 'TypeScript', 'Web Speech API', 'Mapbox', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-45',
    title: 'Movie Recommendation Engine',
    subtitle: 'Collaborative filtering & content preference engine',
    description: 'Collaborative filtering and content-based recommendation system parsing user preferences to suggest tailored film lists.',
    longDescription: 'Recommendation engine scoring user taste profiles to serve personalized movie lists.',
    category: 'AI',
    technologies: ['Python', 'Scikit-learn', 'TMDB API', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-46',
    title: 'Online File Storage Platform',
    subtitle: 'Cloud drive with secure link sharing & preview',
    description: 'Cloud storage drive supporting file uploading, folder creation, link sharing, preview rendering, and storage metrics.',
    longDescription: 'Cloud file locker featuring drag-and-drop uploads, access permissions, and document previews.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'AWS S3', 'Express', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-47',
    title: 'Museum Guide Application',
    subtitle: 'AR exhibit scanner & audio narrative tour guide',
    description: 'Interactive exhibit guide featuring AR artifact scanning, audio narrative playback, and exhibit map routing.',
    longDescription: 'Digital museum companion giving visitors interactive 3D exhibit scans and guided audio tours.',
    category: 'Web',
    technologies: ['React', 'Three.js', 'Tailwind CSS', 'Framer Motion', 'PWA'],
    image: 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-48',
    title: 'Story Writing AI Assistant',
    subtitle: 'LLM character generator & plot twist co-writer',
    description: 'Creative writing workspace offering character generation, plot twist suggestions, and dialogue expansion using LLM prompts.',
    longDescription: 'AI co-writer app helping authors brainstorm character arcs, dialogue options, and narrative twists.',
    category: 'AI',
    technologies: ['Next.js', 'TypeScript', 'OpenAI API', 'Tailwind CSS', 'ProseMirror'],
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-49',
    title: 'Online Voting System',
    subtitle: 'Cryptographically verified election portal',
    description: 'Cryptographically verified online election portal ensuring voter anonymity, tamper-proof ballot counting, and audit logs.',
    longDescription: 'Secure digital voting system utilizing cryptographic hashing to prevent vote manipulation and guarantee transparency.',
    category: 'Full Stack',
    technologies: ['Node.js', 'Express', 'CryptoJS', 'MongoDB', 'React'],
    image: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-50',
    title: 'Stock Market Price Prediction',
    subtitle: 'Financial indicator & technical moving average predictor',
    description: 'Financial indicator analytics app utilizing ARIMA and LSTM models to predict stock price movements and moving averages.',
    longDescription: 'Quantitative finance app forecasting equities using technical indicators and neural time series models.',
    category: 'AI',
    technologies: ['Python', 'TensorFlow', 'Pandas', 'Yahoo Finance API', 'React'],
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-51',
    title: 'File Transfer System',
    subtitle: 'Peer-to-peer WebRTC encrypted browser file transfer',
    description: 'Peer-to-peer WebRTC file transfer utility enabling instant browser-to-browser encrypted file transfers without cloud limits.',
    longDescription: 'Direct P2P file sender transferring files directly between client browsers with end-to-end encryption.',
    category: 'Web',
    technologies: ['React', 'WebRTC', 'Socket.io', 'Tailwind CSS', 'TypeScript'],
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-52',
    title: 'Phishing Website Detection',
    subtitle: 'Browser extension scam site blocker',
    description: 'Browser extension and backend API analyzing DOM elements, SSL certificate data, and URL patterns to block scam sites.',
    longDescription: 'Security extension shielding users from credential harvesting websites through real-time heuristic checks.',
    category: 'AI',
    technologies: ['Python', 'FastAPI', 'Chrome Extension API', 'Scikit-learn'],
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-53',
    title: 'Book Exchange Platform',
    subtitle: 'Community book trading & parcel tracker',
    description: 'Community book swapping platform allowing readers to list books, send trade requests, rate traders, and track parcel deliveries.',
    longDescription: 'Peer-to-peer book swapping service encouraging reader exchanges and catalog sharing.',
    category: 'Web',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-54',
    title: 'Resume Generator Pro',
    subtitle: 'ATS-friendly resume builder with PDF export',
    description: 'Interactive resume builder with live ATS formatting check, PDF export, multi-template selector, and section reordering.',
    longDescription: 'Resume creation tool formatting candidate experience into recruiter-ready templates.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'jsPDF', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-55',
    title: 'Portfolio Builder Studio',
    subtitle: 'No-code portfolio editor with Vercel deployment',
    description: 'No-code web portfolio editor allowing developers to customize themes, import GitHub repositories, and publish live sites.',
    longDescription: 'Developer portfolio publishing tool converting project links into polished glassmorphic websites.',
    category: 'Web',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Monaco Editor', 'Vercel API'],
    image: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-56',
    title: 'Fake News Detection System',
    subtitle: 'BERT transformer news credibility scorer',
    description: 'NLP classifier scoring news articles for credibility, bias, and clickbait indicators using BERT transformers.',
    longDescription: 'Natural language processing classifier rating news reliability and identifying sensationalist bias.',
    category: 'AI',
    technologies: ['Python', 'PyTorch', 'Transformers', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },

  // Image 4
  {
    id: 'proj-57',
    title: 'Online Book Store',
    subtitle: 'Digital bookstore & e-reader web app',
    description: 'Digital bookstore with instant book previews, e-reader mode, genre browsing, cart checkout, and reader reviews.',
    longDescription: 'E-commerce book store offering digital sample previews, instant checkout, and reader reviews.',
    category: 'Web',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-58',
    title: 'Grocery Delivery Platform',
    subtitle: 'Hyperlocal grocery ordering & rider tracker',
    description: 'Instant grocery store delivery platform featuring inventory stock tracking, delivery slots, and real-time rider tracking.',
    longDescription: 'On-demand grocery app facilitating quick delivery of fresh produce and household essentials.',
    category: 'Full Stack',
    technologies: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-59',
    title: 'LinkedIn Network Clone',
    subtitle: 'Professional social network & job portal',
    description: 'Professional networking platform clone supporting connection requests, feed posts, job listings, and message threads.',
    longDescription: 'Professional networking platform featuring career updates, connection feeds, and recruitment portals.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1611944212129-29977ae1398c?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-60',
    title: 'Instagram Social Media Clone',
    subtitle: 'Photo/video feed social platform with stories',
    description: 'Photo & video sharing social platform featuring stories, posts, likes, comment threads, direct messages, and filters.',
    longDescription: 'Media-first social app equipped with image filters, interactive stories, and real-time chat.',
    category: 'Full Stack',
    technologies: ['React', 'Next.js', 'Firebase', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1611262588024-d12430b98920?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-61',
    title: 'WhatsApp Chat Clone',
    subtitle: 'Encrypted real-time messaging & media sharing',
    description: 'Real-time end-to-end encrypted chat web app with status updates, voice notes, media sharing, and group chats.',
    longDescription: 'Real-time messaging platform supporting instant typing indicators, media uploads, and group channels.',
    category: 'Full Stack',
    technologies: ['React', 'Socket.io', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1614680376593-902f749f7b9e?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-62',
    title: 'Student Portal',
    subtitle: 'Academic dashboard & fee payment records',
    description: 'Academic student hub for tracking course schedules, exam grades, attendance percentages, and fee payment receipts.',
    longDescription: 'Student academic dashboard displaying class timetables, semester report cards, and attendance tracking.',
    category: 'Web',
    technologies: ['React', 'TypeScript', 'Node.js', 'MySQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-63',
    title: 'Netflix Advance Platform',
    subtitle: 'Video streaming suite with trailer auto-play',
    description: 'Feature-rich movie streaming platform with trailer auto-play, category carousels, watchlists, and user profiles.',
    longDescription: 'Video streaming platform featuring responsive hero video previews, custom playlists, and title search.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'TMDB API', 'Tailwind CSS', 'Firebase'],
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-64',
    title: 'Quiz & Online Examination Platform',
    subtitle: 'Proctored online exam portal with auto-grading',
    description: 'Secure timed online assessment system featuring anti-cheating tab switch alerts, auto-grading, and leaderboard stats.',
    longDescription: 'Proctored exam software enforcing timer rules, anti-tab switch detection, and instant scoring analytics.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-65',
    title: 'Multiplayer Quiz Game',
    subtitle: 'Real-time WebSockets trivia game',
    description: 'Real-time competitive multiplayer trivia game with WebSockets lobbies, live scores, countdown timers, and streak bonuses.',
    longDescription: 'Real-time trivia game where players join live room codes to compete in timed question rounds.',
    category: 'Web',
    technologies: ['React', 'Socket.io', 'Node.js', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-66',
    title: 'Online Chess Game',
    subtitle: 'WebSockets chess with AI Stockfish engine',
    description: 'Interactive web chess application supporting player vs player WebSockets matches, AI bot difficulty levels, and move history.',
    longDescription: 'Web chess game offering PvP matchmaking, move validation, and Stockfish AI opponent levels.',
    category: 'Web',
    technologies: ['React', 'Chess.js', 'Stockfish API', 'Socket.io', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-67',
    title: 'Warehouse Management System',
    subtitle: 'Barcode tracking & logistics inventory hub',
    description: 'Inventory tracking, barcode scanning integration, bin allocation, stock replenishment alerts, and logistics dispatch management.',
    longDescription: 'Industrial inventory manager tracking SKU locations, incoming shipments, and automated reorder points.',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'Express', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-68',
    title: 'Safety & Parent Collaboration Platform',
    subtitle: 'School bus tracking & parent notification app',
    description: 'School bus tracking, student attendance notifications, parent-teacher messaging, and emergency broadcast channel.',
    longDescription: 'Parent-school communication platform offering real-time bus location tracking and attendance notifications.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'Firebase', 'Tailwind CSS', 'Twilio'],
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-69',
    title: 'Administration Automation Platform',
    subtitle: 'Automated office workflow & digital sign-offs',
    description: 'Automated administrative workflow system digitizing leave approvals, asset allocation, payroll vouchers, and document sign-offs.',
    longDescription: 'Office administrative automation tool standardizing employee leave requests and internal resource approvals.',
    category: 'Full Stack',
    technologies: ['Node.js', 'Express', 'MongoDB', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-70',
    title: 'School Fee Management System',
    subtitle: 'Automated tuition fee collection & receipt portal',
    description: 'Automated student fee collection portal with online payment gateways, installment receipts, late fee rules, and accounting ledger.',
    longDescription: 'School payment portal simplifying tuition collection, generating receipts, and tracking unpaid fees.',
    category: 'Web',
    technologies: ['React', 'Node.js', 'Express', 'MySQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-71',
    title: 'Smart School Operating System',
    subtitle: 'Complete K-12 school ERP & gradebook',
    description: 'Complete K-12 school administration platform covering timetable creation, gradebooks, exam results, and parent communication.',
    longDescription: 'School ERP system combining timetable scheduling, grade entry, attendance, and administrative oversight.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'MongoDB', 'Tailwind CSS', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-72',
    title: 'Regional Language AI Engine',
    subtitle: 'Neural translation & TTS model for Indic languages',
    description: 'Multilingual neural translation and text-to-speech model supporting Indic regional languages for digital accessibility.',
    longDescription: 'Multilingual AI translation service bringing voice synth capabilities to regional languages.',
    category: 'AI',
    technologies: ['Python', 'PyTorch', 'Transformers', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-73',
    title: 'Smart Public Transport System',
    subtitle: 'Live bus/metro tracker & QR ticketing',
    description: 'Real-time city bus & metro location tracking, arrival estimations, ticketing QR codes, and crowding statistics.',
    longDescription: 'Public transit app providing real-time bus locations, passenger crowding indicators, and digital passes.',
    category: 'Full Stack',
    technologies: ['React', 'Leaflet', 'Node.js', 'WebSockets', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-74',
    title: 'FinReach AI',
    subtitle: 'Microfinance credit risk scoring model',
    description: 'AI-driven microfinance credit scoring engine evaluating alternative data points for underbanked entrepreneurs.',
    longDescription: 'Financial inclusion AI scoring creditworthiness through alternative mobile and business activity data.',
    category: 'AI',
    technologies: ['Python', 'XGBoost', 'Scikit-learn', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-75',
    title: 'Hotel Booking Engine',
    subtitle: 'Filterable hotel search & booking portal',
    description: 'Fast hotel reservation portal with filterable amenities, room photos, reviews, instant confirmation, and map views.',
    longDescription: 'Hospitality booking engine with interactive map filtering, amenity checklists, and instant reservation vouchers.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'Node.js', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-76',
    title: 'Movie Ticket Booking System',
    subtitle: 'Cinema seat map & showtime booking app',
    description: 'Cinema seat selection layout, showtime schedule browser, food counter pre-orders, and e-ticket QR generation.',
    longDescription: 'Entertainment booking portal featuring interactive seat maps, snack concessions, and QR entry passes.',
    category: 'Web',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-77',
    title: 'Flight Booking Portal',
    subtitle: 'Airline flight comparison & boarding pass generator',
    description: 'Airline flight search comparison, fare class selection, seat map reservation, baggage add-ons, and boarding passes.',
    longDescription: 'Travel booking system enabling multi-city flight searches, fare class options, and digital boarding passes.',
    category: 'Full Stack',
    technologies: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },

  // Image 5
  {
    id: 'proj-78',
    title: 'Food Delivery System',
    subtitle: 'Interactive restaurant menu & delivery app',
    description: 'Full food ordering flow with interactive restaurant menus, dish search, live delivery map, and driver updates.',
    longDescription: 'Full-service food delivery application supporting cart customization, checkout, and live delivery updates.',
    category: 'Full Stack',
    technologies: ['React', 'Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-79',
    title: 'Digital Banking Platform',
    subtitle: 'Online banking & fund transfer portal',
    description: 'Modern online banking experience with account statements, fund transfers, virtual debit cards, and loan applications.',
    longDescription: 'Fintech online banking interface supporting account history, interbank transfers, and card management.',
    category: 'Full Stack',
    technologies: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-80',
    title: 'Doctor Appointment Booking',
    subtitle: 'Clinical time slot & doctor consultation app',
    description: 'Healthcare portal allowing patients to search specialists, book clinic time slots, upload medical records, and pay online.',
    longDescription: 'Medical portal allowing patients to find specialists, schedule consultations, and manage digital health records.',
    category: 'Web',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-81',
    title: 'Car Rental Management System',
    subtitle: 'Vehicle fleet management & rental contracts',
    description: 'Fleet management and rental booking application handling vehicle availability, driver ID checks, and rental contracts.',
    longDescription: 'Vehicle rental management suite tracking fleet status, reservation schedules, and customer contracts.',
    category: 'Full Stack',
    technologies: ['React', 'TypeScript', 'Node.js', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-82',
    title: 'Travel Planner & Smart Tourism Platform',
    subtitle: 'AI trip itinerary generator & budget estimator',
    description: 'AI-assisted itinerary planner generating custom travel routes, hotel suggestions, attraction bookings, and budget estimates.',
    longDescription: 'AI travel companion creating day-by-day vacation itineraries based on user preferences and budget.',
    category: 'AI',
    technologies: ['Next.js', 'TypeScript', 'OpenAI API', 'Tailwind CSS', 'Mapbox'],
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-83',
    title: 'Property Management System',
    subtitle: 'Lease tracking & tenant maintenance portal',
    description: 'Real estate portfolio management system tracking tenant leases, maintenance maintenance tickets, and rental income.',
    longDescription: 'Property manager dashboard handling tenant contracts, rent collection logs, and repair tickets.',
    category: 'Full Stack',
    technologies: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-84',
    title: 'House Rental & Property Finder',
    subtitle: 'Real estate search portal with virtual tours',
    description: 'Property search portal with interactive map boundaries, virtual 360 tours, owner contact forms, and filterable amenities.',
    longDescription: 'Home searching portal featuring interactive map overlays, photo galleries, and direct owner messaging.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'Leaflet', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-85',
    title: 'Gaming Platform Hub',
    subtitle: 'Browser games portal with global leaderboards',
    description: 'Online web gaming hub hosting browser games, global score leaderboards, player profiles, and tournament brackets.',
    longDescription: 'Online arcade portal offering browser games, score leaderboards, and multiplayer room codes.',
    category: 'Web',
    technologies: ['React', 'PhaserJS', 'Socket.io', 'Tailwind CSS', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-86',
    title: 'Netflix Streaming Hub',
    subtitle: 'Movie player UI with subtitle & watchlist support',
    description: 'High-performance video streaming platform UI with custom video player controls, subtitle support, and watch list.',
    longDescription: 'Media web application offering custom video controls, multi-language subtitle tracks, and category lists.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'Tailwind CSS', 'Video.js', 'Firebase'],
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-87',
    title: 'Spotify Music Player Clone',
    subtitle: 'Web audio player with equalizer & synchronized lyrics',
    description: 'Web audio player with custom playlists, interactive audio equalizer, lyrics sync, artist search, and volume controls.',
    longDescription: 'Web music player featuring interactive audio equalizer visualization, custom playlists, and synchronized lyrics.',
    category: 'Web',
    technologies: ['React', 'Next.js', 'Web Audio API', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-88',
    title: 'Mall Management System',
    subtitle: 'Directory navigation & parking reservation portal',
    description: 'Shopping mall store directory, indoor kiosk navigation, promotional offer wall, and parking space reservation portal.',
    longDescription: 'Shopping center app with interactive indoor store maps, deals catalog, and parking slot reservations.',
    category: 'Web',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-89',
    title: 'Weather App & Forecast Hub',
    subtitle: '7-day forecast & UV radar weather platform',
    description: 'Interactive weather web app rendering 7-day hourly forecasts, UV index, radar maps, and weather alerts via OpenWeather API.',
    longDescription: 'Live weather application delivering detailed meteorological forecasts, radar overlays, and severe storm alerts.',
    category: 'Web',
    technologies: ['React', 'TypeScript', 'OpenWeather API', 'Tailwind CSS', 'Framer Motion'],
    image: 'https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-90',
    title: 'College Management System',
    subtitle: 'Faculty, enrollment & marks portal',
    description: 'Comprehensive college portal managing faculty rosters, department courses, student enrollment, and examination marks.',
    longDescription: 'Higher education ERP managing student registrations, course schedules, faculty assignments, and transcripts.',
    category: 'Full Stack',
    technologies: ['React', 'TypeScript', 'Node.js', 'MySQL', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
  {
    id: 'proj-91',
    title: 'AI Chatbot Assistant',
    subtitle: 'Intelligent support chatbot with custom KB training',
    description: 'Embeddable intelligent customer support chatbot trained on custom knowledge bases for automated ticket resolution.',
    longDescription: 'Embeddable AI support widget answering customer questions using company knowledge base embeddings.',
    category: 'AI',
    technologies: ['Python', 'FastAPI', 'OpenAI API', 'React', 'Tailwind CSS'],
    image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&w=800&q=80',
    githubUrl: 'https://github.com/Krishna8208863439',
    liveUrl: 'https://github.com/Krishna8208863439',
    featured: true,
  },
];

export const EXPERIENCE_DATA: ExperienceItem[] = [
  {
    id: 'exp-1',
    role: 'Senior Full Stack & AI Engineer',
    company: 'TechCorp Innovations',
    location: 'Mumbai, MH (Hybrid)',
    period: '2024 - Present',
    type: 'Full-time',
    description: 'Leading the development of Next.js web applications, generative AI pipelines, and high-speed cloud microservices.',
    responsibilities: [
      'Architected and delivered next-gen enterprise dashboards using Next.js 15, React 19, TypeScript, and Tailwind CSS.',
      'Integrated LLM API workflows and custom Python PyTorch models resulting in a 40% reduction in manual data processing time.',
      'Mentored a team of 5 junior developers, establishing strict CI/CD linting, TypeScript typing standards, and code review practices.',
      'Optimized web vitals score from 68 to 98 across core user-facing portals.',
    ],
    achievements: [
      'Reduced initial page load latency by 65% via Server Components & ISR',
      'Spearheaded the migration of legacy monolith to microservices',
    ],
    skills: ['Next.js', 'React', 'TypeScript', 'Python', 'FastAPI', 'AWS', 'Docker'],
    logoText: 'TC',
  },
  {
    id: 'exp-2',
    role: 'Software Engineer Intern',
    company: 'CloudScale Systems',
    location: 'Remote',
    period: '2023 - 2024',
    type: 'Internship',
    description: 'Engineered REST APIs, database schemas, and interactive React UI components for cloud analytics products.',
    responsibilities: [
      'Developed 12+ reusable React and Tailwind CSS UI components according to Figma design specs.',
      'Optimized MongoDB query performance, indexing frequently read collections to reduce search API latency by 45%.',
      'Implemented Nodemailer automated email dispatch pipelines with HTML email templates and queue retry mechanisms.',
    ],
    achievements: [
      'Received Outstanding Intern Award for top sprint velocity',
      'Authored comprehensive API documentation using Swagger/OpenAPI',
    ],
    skills: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS', 'Git'],
    logoText: 'CS',
  },
  {
    id: 'exp-3',
    role: 'Lead Frontend Developer',
    company: 'DevStudio Agency',
    location: 'Mumbai, MH',
    period: '2022 - 2023',
    type: 'Contract',
    description: 'Designed and deployed responsive web solutions for clients in fintech, e-commerce, and SaaS industries.',
    responsibilities: [
      'Built 15+ custom responsive client websites with Framer Motion animations and dark/light theme persistence.',
      'Ensured 100% WCAG accessibility compliance and mobile responsiveness across all devices.',
    ],
    achievements: [
      'Delivered 100% of client deliverables ahead of target deadline',
      'Increased client conversion rates by an average of 30%',
    ],
    skills: ['JavaScript', 'HTML5/CSS3', 'React', 'Figma', 'UI/UX Design'],
    logoText: 'DS',
  },
];

export const EDUCATION_DATA: EducationItem[] = [
  {
    id: 'edu-1',
    degree: 'Bachelor of Technology (B.Tech)',
    field: 'Computer Science & Engineering',
    institution: 'Sanjay Ghodawat Institute',
    location: '',
    period: '',
    score: 'CGPA: 7.0 / 10.0',
    achievements: [
      'Completed Capstone Project: Autonomous AI Vision & Telemetry System',
    ],
  },
];

export const CERTIFICATES_DATA: CertificateItem[] = [
  // --- CERTIFICATIONS ---
  {
    id: 'cert-1',
    title: 'Python Programming',
    issuer: 'Skill India',
    issueDate: '2024',
    credentialId: 'SKI-PY-8941',
    credentialUrl: 'https://skillindia.gov.in',
    image: '/images/dev_platform.png',
    skills: ['Python', 'Data Structures', 'OOP', 'Algorithms'],
    type: 'Certification',
  },
  {
    id: 'cert-2',
    title: 'Python for Data Science',
    issuer: 'IBM',
    issueDate: '2024',
    credentialId: 'IBM-DS-5542',
    credentialUrl: 'https://ibm.com/credentials',
    image: '/images/ai_saas.png',
    skills: ['Python', 'Pandas', 'NumPy', 'Data Analysis'],
    type: 'Certification',
  },
  {
    id: 'cert-3',
    title: 'Generative AI',
    issuer: 'Microsoft',
    issueDate: '2024',
    credentialId: 'MSFT-GENAI-9903',
    credentialUrl: 'https://microsoft.com/learn',
    image: '/images/dev_platform.png',
    skills: ['Generative AI', 'LLMs', 'Prompt Engineering', 'Azure AI'],
    type: 'Certification',
  },
  {
    id: 'cert-4',
    title: 'Microsoft 365 Copilot',
    issuer: 'Microsoft',
    issueDate: '2024',
    credentialId: 'MSFT-COPILOT-3321',
    credentialUrl: 'https://microsoft.com/learn',
    image: '/images/ai_saas.png',
    skills: ['Microsoft 365', 'Copilot', 'AI Productivity', 'Automation'],
    type: 'Certification',
  },
  {
    id: 'cert-5',
    title: 'Prompt Engineering',
    issuer: 'IBM',
    issueDate: '2024',
    credentialId: 'IBM-PE-7721',
    credentialUrl: 'https://ibm.com/credentials',
    image: '/images/dev_platform.png',
    skills: ['Prompt Engineering', 'LLMs', 'GPT Models', 'AI Workflows'],
    type: 'Certification',
  },
  {
    id: 'cert-6',
    title: 'Web Design & Development',
    issuer: 'Skill India',
    issueDate: '2024',
    credentialId: 'SKI-WEB-3021',
    credentialUrl: 'https://skillindia.gov.in',
    image: '/images/ai_saas.png',
    skills: ['HTML5', 'CSS3', 'JavaScript', 'Responsive Web Design'],
    type: 'Certification',
  },
  {
    id: 'cert-7',
    title: 'AI & ML',
    issuer: 'Unstop',
    issueDate: '2024',
    credentialId: 'UNSTOP-AIML-1029',
    credentialUrl: 'https://unstop.com',
    image: '/images/dev_platform.png',
    skills: ['Artificial Intelligence', 'Machine Learning', 'Scikit-Learn', 'Python'],
    type: 'Certification',
  },
  {
    id: 'cert-8',
    title: 'Modern AI',
    issuer: 'Cisco Networking Academy',
    issueDate: '2024',
    credentialId: 'CISCO-AI-4482',
    credentialUrl: 'https://netacad.com',
    image: '/images/ai_saas.png',
    skills: ['Modern AI', 'Neural Networks', 'Deep Learning', 'Cloud Computing'],
    type: 'Certification',
  },

  // --- HACKATHONS ---
  {
    id: 'hack-1',
    title: 'Quiz Competition',
    issuer: 'Campus Crew',
    issueDate: '2024',
    credentialId: 'CC-QUIZ-2024',
    credentialUrl: 'https://campuscrew.in',
    image: '/images/dev_platform.png',
    skills: ['General Tech Quiz', 'Speed Coding', 'Problem Solving'],
    type: 'Hackathon',
  },
  {
    id: 'hack-2',
    title: 'Frontend Design',
    issuer: 'Frontend War',
    issueDate: '2024',
    credentialId: 'FW-FRONTEND-2024',
    credentialUrl: 'https://frontendwar.dev',
    image: '/images/ai_saas.png',
    skills: ['React', 'CSS Tailwind', 'UI/UX Design', 'Figma'],
    type: 'Hackathon',
  },
  {
    id: 'hack-3',
    title: 'Coding Competition',
    issuer: 'The Ascent Circle',
    issueDate: '2024',
    credentialId: 'TAC-CODING-2024',
    credentialUrl: 'https://ascentcircle.org',
    image: '/images/dev_platform.png',
    skills: ['Competitive Programming', 'Algorithms', 'Data Structures'],
    type: 'Hackathon',
  },
  {
    id: 'hack-4',
    title: 'Inceptia Hackathon',
    issuer: 'Pune Hackathon Summit',
    issueDate: '2024',
    credentialId: 'PUNE-INCEPTIA-2024',
    credentialUrl: 'https://hackathon.org',
    image: '/images/ai_saas.png',
    skills: ['Full Stack Prototype', 'Rapid Development', 'Team Pitch'],
    type: 'Hackathon',
  },
  {
    id: 'hack-5',
    title: 'AI Quest',
    issuer: 'DeVriksh',
    issueDate: '2024',
    credentialId: 'DEV-AIQUEST-2024',
    credentialUrl: 'https://devriksh.com',
    image: '/images/dev_platform.png',
    skills: ['AI Innovation', 'Python', 'Machine Learning', 'NLP'],
    type: 'Hackathon',
  },
  {
    id: 'hack-6',
    title: 'Quiz Competition',
    issuer: 'Devengers',
    issueDate: '2024',
    credentialId: 'DEVENGERS-QUIZ-2024',
    credentialUrl: 'https://devengers.org',
    image: '/images/ai_saas.png',
    skills: ['Core CS Knowledge', 'Logical Reasoning', 'Web Tech'],
    type: 'Hackathon',
  },
  {
    id: 'hack-7',
    title: 'Google Gemini Quiz',
    issuer: 'Campus Crew',
    issueDate: '2024',
    credentialId: 'CC-GEMINI-2024',
    credentialUrl: 'https://campuscrew.in',
    image: '/images/dev_platform.png',
    skills: ['Google Gemini API', 'Generative AI', 'LLMs'],
    type: 'Hackathon',
  },
  {
    id: 'hack-8',
    title: 'Build The Next Big UI',
    issuer: 'TechVerse',
    issueDate: '2024',
    credentialId: 'TV-UIBUILD-2024',
    credentialUrl: 'https://techverse.dev',
    image: '/images/ai_saas.png',
    skills: ['Modern UI/UX', 'Glassmorphism', 'Framer Motion', 'React'],
    type: 'Hackathon',
  },
  {
    id: 'hack-9',
    title: 'Light Grid Control',
    issuer: 'Hack The Matrix',
    issueDate: '2024',
    credentialId: 'HTM-GRID-2024',
    credentialUrl: 'https://hackthematrix.io',
    image: '/images/dev_platform.png',
    skills: ['IoT Systems', 'Grid Automation', 'Embedded Programming'],
    type: 'Hackathon',
  },
  {
    id: 'hack-10',
    title: 'Cool City AI',
    issuer: 'Hacknovate 2026',
    issueDate: '2026',
    credentialId: 'HACKNOVATE-CITYAI-2026',
    credentialUrl: 'https://hacknovate.org',
    image: '/images/ai_saas.png',
    skills: ['Smart Cities', 'AI Telemetry', 'Computer Vision'],
    type: 'Hackathon',
  },

  // --- INTERNSHIPS ---
  {
    id: 'intern-1',
    title: 'Python AI & ML',
    issuer: 'Softron',
    issueDate: '2024',
    credentialId: 'SOFTRON-AIML-2024',
    credentialUrl: 'https://softron.io',
    image: '/images/dev_platform.png',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'Data Processing'],
    type: 'Internship',
  },
  {
    id: 'intern-2',
    title: 'Virtual Data Science',
    issuer: 'N.S.D.C',
    issueDate: '2024',
    credentialId: 'NSDC-VDS-2024',
    credentialUrl: 'https://nsdcindia.org',
    image: '/images/ai_saas.png',
    skills: ['Data Science', 'Statistics', 'Python', 'Data Visualization'],
    type: 'Internship',
  },
  {
    id: 'intern-3',
    title: 'Data Analysis',
    issuer: 'Syntecxhub',
    issueDate: '2024',
    credentialId: 'SYNTECX-DA-2024',
    credentialUrl: 'https://syntecxhub.com',
    image: '/images/dev_platform.png',
    skills: ['Data Cleaning', 'SQL', 'PowerBI', 'Python'],
    type: 'Internship',
  },
  {
    id: 'intern-4',
    title: 'Data Analytics',
    issuer: 'Codec Technologies',
    issueDate: '2024',
    credentialId: 'CODEC-DATA-2024',
    credentialUrl: 'https://codectechnologies.com',
    image: '/images/ai_saas.png',
    skills: ['Data Analytics', 'Excel', 'SQL', 'Python'],
    type: 'Internship',
  },
  {
    id: 'intern-5',
    title: 'AI & ML',
    issuer: 'Codomax',
    issueDate: '2024',
    credentialId: 'CODOMAX-AIML-2024',
    credentialUrl: 'https://codomax.com',
    image: '/images/dev_platform.png',
    skills: ['AI Algorithms', 'Deep Learning', 'PyTorch', 'Model Training'],
    type: 'Internship',
  },
  {
    id: 'intern-6',
    title: 'Data Science',
    issuer: 'Codomax',
    issueDate: '2024',
    credentialId: 'CODOMAX-DS-2024',
    credentialUrl: 'https://codomax.com',
    image: '/images/ai_saas.png',
    skills: ['Data Science', 'Exploratory Analysis', 'Python', 'Machine Learning'],
    type: 'Internship',
  },
  {
    id: 'intern-7',
    title: 'Java Development',
    issuer: 'Cognifyz',
    issueDate: '2024',
    credentialId: 'COGNIFYZ-JAVA-2024',
    credentialUrl: 'https://cognifyz.com',
    image: '/images/dev_platform.png',
    skills: ['Java', 'Spring Boot', 'OOP', 'REST APIs'],
    type: 'Internship',
  },
  {
    id: 'intern-8',
    title: 'Python Development',
    issuer: 'Cognifyz',
    issueDate: '2024',
    credentialId: 'COGNIFYZ-PY-2024',
    credentialUrl: 'https://cognifyz.com',
    image: '/images/ai_saas.png',
    skills: ['Python', 'Django', 'FastAPI', 'Database Integration'],
    type: 'Internship',
  },
  {
    id: 'intern-9',
    title: 'Full Stack Development',
    issuer: 'Thiranex',
    issueDate: '2024',
    credentialId: 'THIRANEX-FS-2024',
    credentialUrl: 'https://thiranex.com',
    image: '/images/dev_platform.png',
    skills: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    type: 'Internship',
  },
  {
    id: 'intern-10',
    title: 'Full Stack Development',
    issuer: 'Cognifyz',
    issueDate: '2024',
    credentialId: 'COGNIFYZ-FS-2024',
    credentialUrl: 'https://cognifyz.com',
    image: '/images/ai_saas.png',
    skills: ['Next.js', 'React', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    type: 'Internship',
  },
];

export const SERVICES_DATA: ServiceItem[] = [
  {
    id: 'srv-1',
    title: 'Full Stack Web Development',
    description: 'End-to-end production web app development using React 19, Next.js 15, TypeScript, and modern backend services.',
    iconName: 'Layout',
    features: ['Server-Side Rendering & ISR', 'Clean Modular Architecture', 'Database & API Integration', 'SEO & Performance Optimized'],
  },
  {
    id: 'srv-2',
    title: 'AI & Machine Learning Solutions',
    description: 'Integrating custom AI models, OpenAI LLMs, computer vision, and predictive analytics pipelines into your applications.',
    iconName: 'Brain',
    features: ['Custom PyTorch/TensorFlow Models', 'LLM Prompt Engineering & RAG', 'Computer Vision & OCR', 'FastAPI Microservice Deployment'],
  },
  {
    id: 'srv-3',
    title: 'Backend & API Architecture',
    description: 'High-throughput, secure REST and GraphQL API endpoints engineered with Node.js, Express, FastAPI, and PostgreSQL/MongoDB.',
    iconName: 'Server',
    features: ['JWT/OAuth Authentication', 'Rate Limiting & Caching', 'Database Optimization', 'Swagger OpenAPI Documentation'],
  },
  {
    id: 'srv-4',
    title: 'UI/UX & Product Design',
    description: 'Crafting modern, glassmorphic, interactive user interfaces with Stripe/Vercel design aesthetic, micro-animations, and full accessibility.',
    iconName: 'Figma',
    features: ['Responsive Mobile-First UI', 'Framer Motion & GSAP Animations', 'Figma Prototyping', 'Dark & Light Theme Systems'],
  },
  {
    id: 'srv-5',
    title: 'Cloud & DevOps Infrastructure',
    description: 'Deploying apps with CI/CD automation on AWS, Vercel, Netlify, and Docker container clusters for zero-downtime scalability.',
    iconName: 'Cloud',
    features: ['Dockerization & Container Ops', 'Vercel / AWS Deployment', 'Automated GitHub Actions CI/CD', 'SSL, DNS & Domain Setup'],
  },
  {
    id: 'srv-6',
    title: 'Tech Consultation & Code Audit',
    description: 'In-depth code reviews, performance bottleneck analysis, refactoring legacy codebases, and architectural guidance.',
    iconName: 'CheckCircle2',
    features: ['Core Web Vitals Optimization', 'Security Vulnerability Scan', 'TypeScript Migration', 'Architecture Recommendations'],
  },
];

export const TESTIMONIALS_DATA: TestimonialItem[] = [
  {
    id: 'test-1',
    name: 'Sarah Jenkins',
    role: 'VP of Product',
    company: 'NexusTech Labs',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    review: 'Krishna is an exceptional developer who transformed our legacy web platform into a lightning-fast Next.js application. His attention to design detail, micro-animations, and AI integration exceeded all expectations!',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'David Chen',
    role: 'CTO & Co-Founder',
    company: 'Streamline AI',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    review: 'Working with Krishna was a breeze. He delivered a complex computer vision dashboard integrated with WebSockets ahead of schedule. Highly recommended for any high-stakes full stack or AI project.',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Elena Rostova',
    role: 'Lead UX Architect',
    company: 'DesignMatrix',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    review: 'Krishna possesses a rare combination of top-tier engineering prowess and an innate visual design sense. He turned our Figma mockups into flawless, production-ready React code.',
    rating: 5,
  },
  {
    id: 'test-4',
    name: 'Michael Vance',
    role: 'Founder',
    company: 'Apex Ventures',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    review: 'From initial consultation to deployment on Vercel, Krishna exhibited clear communication, unmatched speed, and clean code standards. Our users love the new sleek dark-mode portfolio and product experience!',
    rating: 5,
  },
];
