import {
  HighlightStat,
  Skill,
  Project,
  ExperienceItem,
  EducationItem,
  CertificateItem,
  ServiceItem,
  TestimonialItem,
  NavItem,
} from '@/types/portfolio';

export const PERSONAL_INFO = {
  name: 'Krishna Devadkar',
  role: 'Full Stack Developer & AI Engineer',
  roles: [
    'Full Stack Developer',
    'AI Engineer',
    'Python Developer',
    'React Developer',
    'Backend Developer',
  ],
  bio: `Passionate Senior Full Stack Developer and AI Engineer dedicated to building high-performance, scalable web applications and intelligent AI solutions. Experienced in architecting production-ready cloud architectures, training machine learning models, and crafting pixel-perfect, interactive user interfaces with modern web standards.`,
  longBio: `I craft digital products that seamlessly bridge user-centric design with advanced backend intelligence. With expertise spanning Next.js, React, Python, Node.js, and Machine Learning algorithms, I turn complex ideas into elegant, reliable applications. Always striving for clean code, high speed, accessibility, and exceptional visual design reminiscent of Stripe, Vercel, and Linear.`,
  location: 'Mumbai, India (Open to Remote Worldwide)',
  email: 'krishna.devadkar.dev@gmail.com',
  phone: '+91 98765 43210',
  github: 'https://github.com/krishna-devadkar',
  linkedin: 'https://linkedin.com/in/krishna-devadkar',
  instagram: 'https://instagram.com/krishna.dev',
  twitter: 'https://x.com/krishna_dev',
  workingHours: 'Mon - Sat: 9:00 AM - 8:00 PM IST',
  availableForHire: true,
};

export const NAV_ITEMS: NavItem[] = [
  { name: 'Home', href: '#home' },
  { name: 'About', href: '#about' },
  { name: 'Skills', href: '#skills' },
  { name: 'Projects', href: '#projects' },
  { name: 'Experience', href: '#experience' },
  { name: 'Education', href: '#education' },
  { name: 'Certificates', href: '#certificates' },
  { name: 'Services', href: '#services' },
  { name: 'Testimonials', href: '#testimonials' },
  { name: 'Contact', href: '#contact' },
];

export const HIGHLIGHT_STATS: HighlightStat[] = [
  {
    label: 'Years Learning & Building',
    value: 4,
    suffix: '+',
    description: 'Continuous growth, active coding & system architecture',
    iconName: 'Code',
  },
  {
    label: 'Projects Completed',
    value: 25,
    suffix: '+',
    description: 'Full stack web apps, AI models & production microservices',
    iconName: 'FolderCheck',
  },
  {
    label: 'Core Technologies',
    value: 15,
    suffix: '+',
    description: 'Frontend, Backend, AI frameworks & Cloud DevOps tools',
    iconName: 'Cpu',
  },
  {
    label: 'Certifications & Honors',
    value: 10,
    suffix: '+',
    description: 'AWS, TensorFlow, Google & Hackathon Top Awards',
    iconName: 'Award',
  },
];

export const SKILLS_DATA: Skill[] = [
  // Frontend
  { name: 'HTML5', category: 'Frontend', level: 95, iconName: 'FileCode' },
  { name: 'CSS3', category: 'Frontend', level: 92, iconName: 'Palette' },
  { name: 'JavaScript', category: 'Frontend', level: 95, iconName: 'Zap', popular: true },
  { name: 'TypeScript', category: 'Frontend', level: 92, iconName: 'ShieldCheck', popular: true },
  { name: 'React', category: 'Frontend', level: 94, iconName: 'Atom', popular: true },
  { name: 'Next.js', category: 'Frontend', level: 92, iconName: 'Layers', popular: true },
  { name: 'Tailwind CSS', category: 'Frontend', level: 95, iconName: 'Wind', popular: true },

  // Backend
  { name: 'Node.js', category: 'Backend', level: 90, iconName: 'Server', popular: true },
  { name: 'Express.js', category: 'Backend', level: 88, iconName: 'Workflow' },
  { name: 'Python', category: 'Backend', level: 92, iconName: 'Terminal', popular: true },
  { name: 'Flask', category: 'Backend', level: 85, iconName: 'Flame' },
  { name: 'FastAPI', category: 'Backend', level: 88, iconName: 'Cpu' },

  // Database
  { name: 'MongoDB', category: 'Database', level: 88, iconName: 'Database', popular: true },
  { name: 'PostgreSQL', category: 'Database', level: 86, iconName: 'HardDrive' },
  { name: 'MySQL', category: 'Database', level: 84, iconName: 'Table' },
  { name: 'Firebase', category: 'Database', level: 85, iconName: 'Flame' },

  // AI & ML
  { name: 'TensorFlow', category: 'AI', level: 85, iconName: 'BrainCircuit', popular: true },
  { name: 'PyTorch', category: 'AI', level: 82, iconName: 'Sparkles' },
  { name: 'OpenCV', category: 'AI', level: 84, iconName: 'Eye' },
  { name: 'Machine Learning', category: 'AI', level: 88, iconName: 'Activity', popular: true },
  { name: 'Deep Learning', category: 'AI', level: 85, iconName: 'Network' },

  // Cloud & DevOps
  { name: 'AWS', category: 'Cloud', level: 84, iconName: 'Cloud', popular: true },
  { name: 'Vercel', category: 'Cloud', level: 94, iconName: 'Triangle' },
  { name: 'Netlify', category: 'Cloud', level: 90, iconName: 'Globe' },
  { name: 'Docker', category: 'Cloud', level: 82, iconName: 'Box', popular: true },

  // Tools
  { name: 'Git', category: 'Tools', level: 92, iconName: 'GitBranch' },
  { name: 'GitHub', category: 'Tools', level: 94, iconName: 'Github' },
  { name: 'VS Code', category: 'Tools', level: 96, iconName: 'Code2' },
  { name: 'Postman', category: 'Tools', level: 90, iconName: 'Send' },
  { name: 'Figma', category: 'Tools', level: 86, iconName: 'Figma' },
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 'neural-vision-ai',
    title: 'NeuralVision AI',
    subtitle: 'Autonomous Multimodal AI Vision & Analytics Platform',
    description: 'Enterprise-grade computer vision suite capable of real-time object detection, facial recognition, and automated document data extraction.',
    longDescription: 'NeuralVision AI utilizes custom PyTorch and OpenCV models deployed via FastAPI microservices and wrapped in an ultra-responsive Next.js frontend with WebSockets for dynamic live frame rendering. Includes fine-tuned object tracking, edge detection, and real-time inference telemetry.',
    category: 'AI',
    technologies: ['Next.js', 'Python', 'FastAPI', 'PyTorch', 'OpenCV', 'Tailwind CSS', 'Docker'],
    features: [
      'Real-time video stream processing via WebSockets',
      'Custom fine-tuned YOLOv8 & ResNet models',
      'Automated PDF & document OCR extraction',
      'Interactive dashboard with live FPS & confidence metrics',
    ],
    image: '/images/ai_saas.png',
    githubUrl: 'https://github.com/krishna-devadkar/neural-vision-ai',
    liveUrl: 'https://neural-vision-ai.vercel.app',
    featured: true,
  },
  {
    id: 'devpulse-cloud',
    title: 'DevPulse Workspace',
    subtitle: 'Developer Productivity & Real-time CI/CD Telemetry Hub',
    description: 'All-in-one workspace dashboard for software engineering teams featuring live GitHub metrics, build pipelines, and automated bug detection.',
    longDescription: 'DevPulse combines developer metrics, automated PR reviews using OpenAI GPT-4, and real-time server health monitoring in a single unified dark-mode interface built with Next.js App Router, TypeScript, and Tailwind CSS.',
    category: 'Full Stack',
    technologies: ['React 19', 'Next.js 15', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS', 'Framer Motion'],
    features: [
      'Live WebSockets telemetry & build status alerts',
      'AI-assisted Pull Request summaries & security audits',
      'Role-based access control (RBAC) & team workspace billing',
      'Glassmorphic dark design system with dynamic keyboard shortcuts',
    ],
    image: '/images/dev_platform.png',
    githubUrl: 'https://github.com/krishna-devadkar/devpulse-cloud',
    liveUrl: 'https://devpulse-cloud.vercel.app',
    featured: true,
  },
  {
    id: 'omnia-storefront',
    title: 'Omnia E-Commerce Platform',
    subtitle: 'Ultra-Fast Headless E-Commerce System with AI Recommendations',
    description: 'High-conversion headless shopping platform powered by Next.js Server Components, Stripe payments, and personalized vector search recommendations.',
    longDescription: 'Engineered for sub-100ms page loads, Omnia leverages incremental static regeneration (ISR), Redis caching, Stripe Checkout, and automated email order receipts via Nodemailer.',
    category: 'Web',
    technologies: ['Next.js', 'React', 'Tailwind CSS', 'Stripe API', 'MongoDB', 'Redis', 'Nodemailer'],
    features: [
      'Sub-second page load speeds with ISR & Next Image optimization',
      'Vector similarity search for personalized product recommendations',
      'Seamless 3-step checkout with Stripe Webhooks',
      'Full inventory management backoffice dashboard',
    ],
    image: '/images/dev_platform.png',
    githubUrl: 'https://github.com/krishna-devadkar/omnia-storefront',
    liveUrl: 'https://omnia-storefront.vercel.app',
    featured: true,
  },
  {
    id: 'codesense-mobile',
    title: 'CodeSense Mobile AI',
    subtitle: 'Cross-platform Mobile AI Code Debugger & Syntax Copilot',
    description: 'Mobile companion application allowing developers to scan code snippets, run automated diagnostic tests, and receive immediate AI refactoring recommendations.',
    longDescription: 'Built with React Native & Expo, CodeSense provides instant offline syntax highlights, voice-prompted code searches, and cloud sync across dev devices.',
    category: 'Mobile',
    technologies: ['React Native', 'Expo', 'TypeScript', 'OpenAI API', 'Tailwind CSS', 'Node.js'],
    features: [
      'Camera-based OCR snippet scanning & syntax parsing',
      'Instant AI-powered bug fix recommendations',
      'Offline code snippet vault with encrypted local storage',
      'Biometric authentication (FaceID / Fingerprint)',
    ],
    image: '/images/ai_saas.png',
    githubUrl: 'https://github.com/krishna-devadkar/codesense-mobile',
    liveUrl: 'https://codesense-app.vercel.app',
    featured: false,
  },
  {
    id: 'predictive-lead-ml',
    title: 'Predictive Lead ML Engine',
    subtitle: 'Machine Learning Customer Conversion & Churn Forecaster',
    description: 'Predictive analytics pipeline that analyzes customer behavioral logs to forecast churn risks and calculate lead conversion probabilities.',
    longDescription: 'Developed using Python, Scikit-learn, XGBoost, and Flask, this system processes enterprise CRM events to deliver highly accurate customer scoring metrics directly into sales dashboards.',
    category: 'Machine Learning',
    technologies: ['Python', 'Scikit-learn', 'XGBoost', 'Flask', 'Pandas', 'PostgreSQL', 'Chart.js'],
    features: [
      '94.2% accuracy rating on lead conversion scoring',
      'Automated nightly model re-training pipelines',
      'Interactive risk heatmaps and feature importance plots',
      'REST API integration with Salesforce and HubSpot',
    ],
    image: '/images/ai_saas.png',
    githubUrl: 'https://github.com/krishna-devadkar/predictive-lead-ml',
    liveUrl: 'https://predictive-lead-ml.vercel.app',
    featured: false,
  },
  {
    id: 'distributed-vault-api',
    title: 'Distributed Vault API',
    subtitle: 'High-Throughput Encrypted Microservice API Architecture',
    description: 'Resilient backend microservices architecture built for high-concurrency token authentication, rate limiting, and encrypted secret management.',
    longDescription: 'Built using Express, TypeScript, and MongoDB with distributed Redis session locks, maintaining 99.99% uptime under simulated burst traffic of 10,000 req/sec.',
    category: 'Full Stack',
    technologies: ['Node.js', 'Express', 'TypeScript', 'MongoDB', 'Redis', 'Docker', 'JWT'],
    features: [
      'AES-256 GCM encryption at rest and in transit',
      'Token bucket rate-limiting middleware',
      'Comprehensive OpenAPI / Swagger document hub',
      'Automated Docker Swarm health-checks',
    ],
    image: '/images/dev_platform.png',
    githubUrl: 'https://github.com/krishna-devadkar/distributed-vault-api',
    liveUrl: 'https://distributed-vault.vercel.app',
    featured: false,
  },
];

export const EXPERIENCE_DATA: ExperienceItem[] = [
  {
    id: 'exp-1',
    role: 'Senior Full Stack & AI Engineer',
    company: 'TechCorp Innovations',
    location: 'Mumbai, MH (Hybrid)',
    period: '2024 - Present',
    type: 'Full-time',
    description: 'Leading the development of Next.js web applications, generative AI pipelines, and high-speed cloud microservices.',
    responsibilities: [
      'Architected and delivered next-gen enterprise dashboards using Next.js 15, React 19, TypeScript, and Tailwind CSS.',
      'Integrated LLM API workflows and custom Python PyTorch models resulting in a 40% reduction in manual data processing time.',
      'Mentored a team of 5 junior developers, establishing strict CI/CD linting, TypeScript typing standards, and code review practices.',
      'Optimized web vitals score from 68 to 98 across core user-facing portals.',
    ],
    achievements: [
      'Reduced initial page load latency by 65% via Server Components & ISR',
      'Spearheaded the migration of legacy monolith to microservices',
    ],
    skills: ['Next.js', 'React', 'TypeScript', 'Python', 'FastAPI', 'AWS', 'Docker'],
    logoText: 'TC',
  },
  {
    id: 'exp-2',
    role: 'Software Engineer Intern',
    company: 'CloudScale Systems',
    location: 'Remote',
    period: '2023 - 2024',
    type: 'Internship',
    description: 'Engineered REST APIs, database schemas, and interactive React UI components for cloud analytics products.',
    responsibilities: [
      'Developed 12+ reusable React and Tailwind CSS UI components according to Figma design specs.',
      'Optimized MongoDB query performance, indexing frequently read collections to reduce search API latency by 45%.',
      'Implemented Nodemailer automated email dispatch pipelines with HTML email templates and queue retry mechanisms.',
    ],
    achievements: [
      'Received Outstanding Intern Award for top sprint velocity',
      'Authored comprehensive API documentation using Swagger/OpenAPI',
    ],
    skills: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS', 'Git'],
    logoText: 'CS',
  },
  {
    id: 'exp-3',
    role: 'Lead Frontend Developer',
    company: 'DevStudio Agency',
    location: 'Mumbai, MH',
    period: '2022 - 2023',
    type: 'Contract',
    description: 'Designed and deployed responsive web solutions for clients in fintech, e-commerce, and SaaS industries.',
    responsibilities: [
      'Built 15+ custom responsive client websites with Framer Motion animations and dark/light theme persistence.',
      'Ensured 100% WCAG accessibility compliance and mobile responsiveness across all devices.',
    ],
    achievements: [
      'Delivered 100% of client deliverables ahead of target deadline',
      'Increased client conversion rates by an average of 30%',
    ],
    skills: ['JavaScript', 'HTML5/CSS3', 'React', 'Figma', 'UI/UX Design'],
    logoText: 'DS',
  },
];

export const EDUCATION_DATA: EducationItem[] = [
  {
    id: 'edu-1',
    degree: 'Bachelor of Technology (B.Tech)',
    field: 'Computer Science & Engineering (Artificial Intelligence & Machine Learning)',
    institution: 'St. John College of Engineering and Management (SJCEM)',
    location: 'Mumbai, MH',
    period: '2021 - 2025',
    score: 'CGPA: 9.4 / 10.0',
    achievements: [
      'Graduated First Class with Distinction in CSE (AI & ML)',
      'Lead Technical Coordinator for Annual National Tech Symposium',
      'Published research paper on Convolutional Neural Networks for Image Segmentation',
      'Completed Capstone Project: Autonomous AI Vision & Telemetry System',
    ],
  },
  {
    id: 'edu-2',
    degree: 'Higher Secondary Certificate (HSC - 12th)',
    field: 'Science Stream (Physics, Chemistry, Mathematics, Computer Science)',
    institution: 'State Board of Secondary & Higher Secondary Education',
    location: 'Mumbai, MH',
    period: '2019 - 2021',
    score: 'Percentage: 92.5%',
    achievements: [
      'Top Ranker in Computer Science & Mathematics',
      'Winner of Regional Inter-College Science Quiz',
    ],
  },
];

export const CERTIFICATES_DATA: CertificateItem[] = [
  {
    id: 'cert-1',
    title: 'AWS Certified Solutions Architect – Associate',
    issuer: 'Amazon Web Services (AWS)',
    issueDate: '2024',
    credentialId: 'AWS-ASA-894102',
    credentialUrl: 'https://aws.amazon.com/verification',
    image: '/images/dev_platform.png',
    skills: ['AWS', 'Cloud Architecture', 'S3', 'Lambda', 'EC2'],
    type: 'Certification',
  },
  {
    id: 'cert-2',
    title: 'TensorFlow Developer Certificate',
    issuer: 'Google Brain / TensorFlow',
    issueDate: '2024',
    credentialId: 'TF-DEV-55421',
    credentialUrl: 'https://www.credential.net',
    image: '/images/ai_saas.png',
    skills: ['TensorFlow', 'Deep Learning', 'Computer Vision', 'NLP'],
    type: 'Certification',
  },
  {
    id: 'cert-3',
    title: 'Meta Senior Front-End Developer Specialization',
    issuer: 'Meta / Coursera',
    issueDate: '2023',
    credentialId: 'META-FE-99031',
    credentialUrl: 'https://coursera.org/verify',
    image: '/images/dev_platform.png',
    skills: ['React', 'Next.js', 'Advanced JavaScript', 'Web Performance'],
    type: 'Certification',
  },
  {
    id: 'cert-4',
    title: '1st Place Winner - National AI Innovation Hackathon',
    issuer: 'National Tech Summit',
    issueDate: '2024',
    credentialId: 'HACK-AI-WINNER-2024',
    credentialUrl: 'https://hackathon.org/winners',
    image: '/images/ai_saas.png',
    skills: ['Rapid Prototyping', 'Generative AI', 'Python', 'Full Stack'],
    type: 'Hackathon',
  },
  {
    id: 'cert-5',
    title: 'Open Source Excellence Award',
    issuer: 'Global Developer Foundation',
    issueDate: '2023',
    credentialId: 'OS-CONTRIB-7721',
    credentialUrl: 'https://opensource.org',
    image: '/images/dev_platform.png',
    skills: ['Open Source', 'GitHub', 'React Ecosystem', 'Community Engagement'],
    type: 'Award',
  },
  {
    id: 'cert-6',
    title: 'Deep Learning & Neural Networks Specialist',
    issuer: 'DeepLearning.AI',
    issueDate: '2023',
    credentialId: 'DLAI-DL-30219',
    credentialUrl: 'https://deeplearning.ai',
    image: '/images/ai_saas.png',
    skills: ['PyTorch', 'CNNs', 'RNNs', 'Transformers'],
    type: 'Certification',
  },
];

export const SERVICES_DATA: ServiceItem[] = [
  {
    id: 'srv-1',
    title: 'Full Stack Web Development',
    description: 'End-to-end production web app development using React 19, Next.js 15, TypeScript, and modern backend services.',
    iconName: 'Layout',
    features: ['Server-Side Rendering & ISR', 'Clean Modular Architecture', 'Database & API Integration', 'SEO & Performance Optimized'],
  },
  {
    id: 'srv-2',
    title: 'AI & Machine Learning Solutions',
    description: 'Integrating custom AI models, OpenAI LLMs, computer vision, and predictive analytics pipelines into your applications.',
    iconName: 'Brain',
    features: ['Custom PyTorch/TensorFlow Models', 'LLM Prompt Engineering & RAG', 'Computer Vision & OCR', 'FastAPI Microservice Deployment'],
  },
  {
    id: 'srv-3',
    title: 'Backend & API Architecture',
    description: 'High-throughput, secure REST and GraphQL API endpoints engineered with Node.js, Express, FastAPI, and PostgreSQL/MongoDB.',
    iconName: 'Server',
    features: ['JWT/OAuth Authentication', 'Rate Limiting & Caching', 'Database Optimization', 'Swagger OpenAPI Documentation'],
  },
  {
    id: 'srv-4',
    title: 'UI/UX & Product Design',
    description: 'Crafting modern, glassmorphic, interactive user interfaces with Stripe/Vercel design aesthetic, micro-animations, and full accessibility.',
    iconName: 'Figma',
    features: ['Responsive Mobile-First UI', 'Framer Motion & GSAP Animations', 'Figma Prototyping', 'Dark & Light Theme Systems'],
  },
  {
    id: 'srv-5',
    title: 'Cloud & DevOps Infrastructure',
    description: 'Deploying apps with CI/CD automation on AWS, Vercel, Netlify, and Docker container clusters for zero-downtime scalability.',
    iconName: 'Cloud',
    features: ['Dockerization & Container Ops', 'Vercel / AWS Deployment', 'Automated GitHub Actions CI/CD', 'SSL, DNS & Domain Setup'],
  },
  {
    id: 'srv-6',
    title: 'Tech Consultation & Code Audit',
    description: 'In-depth code reviews, performance bottleneck analysis, refactoring legacy codebases, and architectural guidance.',
    iconName: 'CheckCircle2',
    features: ['Core Web Vitals Optimization', 'Security Vulnerability Scan', 'TypeScript Migration', 'Architecture Recommendations'],
  },
];

export const TESTIMONIALS_DATA: TestimonialItem[] = [
  {
    id: 'test-1',
    name: 'Sarah Jenkins',
    role: 'VP of Product',
    company: 'NexusTech Labs',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    review: 'Krishna is an exceptional developer who transformed our legacy web platform into a lightning-fast Next.js application. His attention to design detail, micro-animations, and AI integration exceeded all expectations!',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'David Chen',
    role: 'CTO & Co-Founder',
    company: 'Streamline AI',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    review: 'Working with Krishna was a breeze. He delivered a complex computer vision dashboard integrated with WebSockets ahead of schedule. Highly recommended for any high-stakes full stack or AI project.',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Elena Rostova',
    role: 'Lead UX Architect',
    company: 'DesignMatrix',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    review: 'Krishna possesses a rare combination of top-tier engineering prowess and an innate visual design sense. He turned our Figma mockups into flawless, production-ready React code.',
    rating: 5,
  },
  {
    id: 'test-4',
    name: 'Michael Vance',
    role: 'Founder',
    company: 'Apex Ventures',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    review: 'From initial consultation to deployment on Vercel, Krishna exhibited clear communication, unmatched speed, and clean code standards. Our users love the new sleek dark-mode portfolio and product experience!',
    rating: 5,
  },
];
